<?php

/**
 * Auto-generated stub file for Moodle's mod/lti/classes/local/ltiservice/resource_base.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
/**
 * This file contains an abstract definition of an LTI resource
 *
 * @package    mod_lti
 * @copyright  2014 Vital Source Technologies http://vitalsource.com
 * @author     Stephen Vickers
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
namespace mod_lti\local\ltiservice;

/**
 * The mod_lti\local\ltiservice\resource_base class.
 *
 * @package    mod_lti
 * @since      Moodle 2.8
 * @copyright  2014 Vital Source Technologies http://vitalsource.com
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
abstract class resource_base
{
    /**  HTTP Post method */
    const HTTP_POST = 'POST';
    /**  HTTP Get method */
    const HTTP_GET = 'GET';
    /**  HTTP Put method */
    const HTTP_PUT = 'PUT';
    /**  HTTP Delete method */
    const HTTP_DELETE = 'DELETE';
    /** @var service_base Service associated with this resource. */
    private $service;
    /** @var string Type for this resource. */
    protected $type;
    /** @var string ID for this resource. */
    protected $id;
    /** @var string Template for this resource. */
    protected $template;
    /** @var array Custom parameter substitution variables associated with this resource. */
    protected $variables;
    /** @var array Media types supported by this resource. */
    protected $formats;
    /** @var array HTTP actions supported by this resource. */
    protected $methods;
    /** @var array Template variables parsed from the resource template. */
    protected $params;
    /**
     * Class constructor.
     *
     * @param service_base $service Service instance
     */
    public function __construct($service)
    {
    }
    /**
     * Get the resource ID.
     *
     * @return string
     */
    public function get_id()
    {
    }
    /**
     * Get the resource template.
     *
     * @return string
     */
    public function get_template()
    {
    }
    /**
     * Get the resource path.
     *
     * @return string
     */
    public function get_path()
    {
    }
    /**
     * Get the resource type.
     *
     * @return string
     */
    public function get_type()
    {
    }
    /**
     * Get the resource's service.
     *
     * @return service_base
     */
    public function get_service()
    {
    }
    /**
     * Get the resource methods.
     *
     * @return array
     */
    public function get_methods()
    {
    }
    /**
     * Get the resource media types.
     *
     * @return array
     */
    public function get_formats()
    {
    }
    /**
     * Get the resource template variables.
     *
     * @return array
     */
    public function get_variables()
    {
    }
    /**
     * Get the resource fully qualified endpoint.
     *
     * @return string
     */
    public function get_endpoint()
    {
    }
    /**
     * Execute the request for this resource.
     *
     * @param response $response  Response object for this request.
     */
    abstract public function execute($response);
    /**
     * Check to make sure the request is valid.
     *
     * @param int $typeid                   The typeid we want to use
     * @param string $body                  Body of HTTP request message
     * @param string[] $scopes              Array of scope(s) required for incoming request
     *
     * @return boolean
     */
    public function check_tool($typeid, $body = null, $scopes = null)
    {
    }
    /**
     * Check to make sure the request is valid.
     *
     * @param string $toolproxyguid Consumer key
     * @param string $body          Body of HTTP request message
     *
     * @return boolean
     * @deprecated since Moodle 3.7 MDL-62599 - please do not use this function any more.
     * @see resource_base::check_tool()
     */
    public function check_tool_proxy($toolproxyguid, $body = null)
    {
    }
    /**
     * Check to make sure the request is valid.
     *
     * @param int $typeid                   The typeid we want to use
     * @param int $contextid                The course we are at
     * @param string $permissionrequested   The permission to be checked
     * @param string $body                  Body of HTTP request message
     *
     * @return boolean
     * @deprecated since Moodle 3.7 MDL-62599 - please do not use this function any more.
     * @see resource_base::check_tool()
     */
    public function check_type($typeid, $contextid, $permissionrequested, $body = null)
    {
    }
    /**
     * get permissions from the config of the tool for that resource
     *
     * @param int $ltitype Type of LTI
     * @return array with the permissions related to this resource by the $ltitype or empty if none.
     * @deprecated since Moodle 3.7 MDL-62599 - please do not use this function any more.
     * @see resource_base::check_tool()
     */
    public function get_permissions($ltitype)
    {
    }
    /**
     * Parse a value for custom parameter substitution variables.
     *
     * @param string $value String to be parsed
     *
     * @return string
     */
    public function parse_value($value)
    {
    }
    /**
     * Parse the template for variables.
     *
     * @return array
     */
    protected function parse_template()
    {
    }
}