<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/DataCatalog/GoogleCloudDatacatalogV1RenameTagTemplateFieldEnumValueRequest.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\DataCatalog {
    class GoogleCloudDatacatalogV1RenameTagTemplateFieldEnumValueRequest extends \Google\Model
    {
        /**
         * Required. The new display name of the enum value. For example,
         * `my_new_enum_value`.
         *
         * @var string
         */
        public $newEnumValueDisplayName;
        /**
         * Required. The new display name of the enum value. For example,
         * `my_new_enum_value`.
         *
         * @param string $newEnumValueDisplayName
         */
        public function setNewEnumValueDisplayName($newEnumValueDisplayName)
        {
        }
        /**
         * @return string
         */
        public function getNewEnumValueDisplayName()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\DataCatalog\GoogleCloudDatacatalogV1RenameTagTemplateFieldEnumValueRequest registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_DataCatalog_GoogleCloudDatacatalogV1RenameTagTemplateFieldEnumValueRequest extends \Google\Service\DataCatalog\GoogleCloudDatacatalogV1RenameTagTemplateFieldEnumValueRequest
    {
    }
}