<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/SA360/GoogleAdsSearchads360V23ServicesMetricAttributes.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\SA360 {
    class GoogleAdsSearchads360V23ServicesMetricAttributes extends \Google\Collection
    {
        protected $collection_key = 'attributes';
        protected $attributesType = GoogleAdsSearchads360V23ServicesMetricAttributesAttribute::class;
        protected $attributesDataType = 'array';
        /**
         * The name of the metric.
         *
         * @var string
         */
        public $name;
        /**
         * The attributes of the metric.
         *
         * @param GoogleAdsSearchads360V23ServicesMetricAttributesAttribute[] $attributes
         */
        public function setAttributes($attributes)
        {
        }
        /**
         * @return GoogleAdsSearchads360V23ServicesMetricAttributesAttribute[]
         */
        public function getAttributes()
        {
        }
        /**
         * The name of the metric.
         *
         * @param string $name
         */
        public function setName($name)
        {
        }
        /**
         * @return string
         */
        public function getName()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\SA360\GoogleAdsSearchads360V23ServicesMetricAttributes registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_SA360_GoogleAdsSearchads360V23ServicesMetricAttributes extends \Google\Service\SA360\GoogleAdsSearchads360V23ServicesMetricAttributes
    {
    }
}