<?php

/**
 * Auto-generated stub file for Moodle's grade/edit/tree/lib.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
class grade_edit_tree
{
    var $columns = array();
    /**
     * @var object $gtree          @see grade/lib.php
     */
    var $gtree;
    /**
     * @var grade_plugin_return @see grade/lib.php
     */
    var $gpr;
    /**
     * @var string              $moving The eid of the category or item being moved
     */
    var $moving;
    var $deepest_level;
    var $uses_extra_credit = false;
    var $uses_weight = false;
    /**
     * Constructor
     */
    function grade_edit_tree($gtree, $moving = false, $gpr)
    {
    }
    /**
     * Recursive function for building the table holding the grade categories and items,
     * with CSS indentation and styles.
     *
     * @param array               $element The current tree element being rendered
     * @param boolean             $totals Whether or not to print category grade items (category totals)
     * @param array               $parents An array of parent categories for the current element (used for indentation and row classes)
     *
     * @return string HTML
     */
    function build_html_tree($element, $totals, $parents, &$categories, $level, &$row_count)
    {
    }
    /**
     * Given a grade_item object, returns a labelled input if an aggregation coefficient (weight or extra credit) applies to it.
     * @param grade_item $item
     * @param string type "extra" or "weight": the type of the column hosting the weight input
     * @return string HTML
     */
    function get_weight_input($item, $type)
    {
    }
    /**
     * Given an element of the grade tree, returns whether it is deletable or not (only manual grade items are deletable)
     *
     * @param array $element
     * @return bool
     */
    function element_deletable($element)
    {
    }
    /**
     * Given the grade tree and an array of element ids (e.g. c15, i42), and expecting the 'moveafter' URL param,
     * moves the selected items to the requested location. Then redirects the user to the given $returnurl
     *
     * @param object $gtree The grade tree (a recursive representation of the grade categories and grade items)
     * @param array $eids
     * @param string $returnurl
     */
    function move_elements($eids, $returnurl)
    {
    }
    /**
     * Recurses through the entire grade tree to find and return the maximum depth of the tree.
     * This should be run only once from the root element (course category), and is used for the
     * indentation of the Name column's cells (colspan)
     *
     * @param array $element An array of values representing a grade tree's element (all grade items in this case)
     * @param int $level The level of the current recursion
     * @param int $deepest_level A value passed to each subsequent level of recursion and incremented if $level > $deepest_level
     * @return int Deepest level
     */
    function get_deepest_level($element, $level = 0, $deepest_level = 1)
    {
    }
}
class grade_edit_tree_column
{
    var $forced;
    var $hidden;
    var $forced_hidden;
    var $advanced_hidden;
    var $hide_when_moving = true;
    function factory($name, $params = array())
    {
    }
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
    function is_hidden($mode = 'simple')
    {
    }
}
class grade_edit_tree_column_category extends grade_edit_tree_column
{
    var $forced;
    var $advanced;
    function grade_edit_tree_column_category($name)
    {
    }
    function is_hidden($mode = 'simple')
    {
    }
}
class grade_edit_tree_column_name extends grade_edit_tree_column
{
    var $forced = false;
    var $hidden = false;
    var $forced_hidden = false;
    var $advanced_hidden = false;
    var $deepest_level = 1;
    var $hide_when_moving = false;
    function grade_edit_tree_column_name($params)
    {
    }
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
    function is_hidden($mode = 'simple')
    {
    }
}
class grade_edit_tree_column_aggregation extends grade_edit_tree_column_category
{
    function grade_edit_tree_column_aggregation($params)
    {
    }
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
}
class grade_edit_tree_column_extracredit extends grade_edit_tree_column
{
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
    function is_hidden($mode = 'simple')
    {
    }
}
class grade_edit_tree_column_weight extends grade_edit_tree_column
{
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
    function is_hidden($mode = 'simple')
    {
    }
}
class grade_edit_tree_column_range extends grade_edit_tree_column
{
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
    function is_hidden($mode = 'simple')
    {
    }
}
class grade_edit_tree_column_aggregateonlygraded extends grade_edit_tree_column_category
{
    function grade_edit_tree_column_aggregateonlygraded($params)
    {
    }
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
}
class grade_edit_tree_column_aggregatesubcats extends grade_edit_tree_column_category
{
    function grade_edit_tree_column_aggregatesubcats($params)
    {
    }
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
}
class grade_edit_tree_column_aggregateoutcomes extends grade_edit_tree_column_category
{
    function grade_edit_tree_column_aggregateoutcomes($params)
    {
    }
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
    function is_hidden($mode = 'simple')
    {
    }
}
class grade_edit_tree_column_droplow extends grade_edit_tree_column_category
{
    function grade_edit_tree_column_droplow($params)
    {
    }
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
}
class grade_edit_tree_column_keephigh extends grade_edit_tree_column_category
{
    function grade_edit_tree_column_keephigh($params)
    {
    }
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
}
class grade_edit_tree_column_multfactor extends grade_edit_tree_column
{
    function grade_edit_tree_column_multfactor($params)
    {
    }
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
    function is_hidden($mode = 'simple')
    {
    }
}
class grade_edit_tree_column_plusfactor extends grade_edit_tree_column
{
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
    function is_hidden($mode = 'simple')
    {
    }
}
class grade_edit_tree_column_actions extends grade_edit_tree_column
{
    function grade_edit_tree_column_actions($params)
    {
    }
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
    function is_hidden($mode = 'simple')
    {
    }
}
class grade_edit_tree_column_select extends grade_edit_tree_column
{
    function get_header_cell()
    {
    }
    function get_category_cell($category, $levelclass, $params)
    {
    }
    function get_item_cell($item, $params)
    {
    }
    function is_hidden($mode = 'simple')
    {
    }
}