<?php

/**
 * Auto-generated stub file for Moodle's enrol/flatfile/db/upgrade.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
function xmldb_enrol_flatfile_upgrade($oldversion)
{
}