<?php

/**
 * Auto-generated stub file for Moodle's mod/assign/feedback/editpdf/fpdi/src/FpdfTplTrait.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/**
 * This file is part of FPDI
 *
 * @package   setasign\Fpdi
 * @copyright Copyright (c) 2024 Setasign GmbH & Co. KG (https://www.setasign.com)
 * @license   http://opensource.org/licenses/mit-license The MIT License
 */
namespace setasign\Fpdi;

/**
 * Trait FpdfTplTrait
 *
 * This trait adds a templating feature to FPDF and tFPDF.
 */
trait FpdfTplTrait
{
    /**
     * Data of all created templates.
     *
     * @var array
     */
    protected $templates = [];
    /**
     * The template id for the currently created template.
     *
     * @var null|int
     */
    protected $currentTemplateId;
    /**
     * A counter for template ids.
     *
     * @var int
     */
    protected $templateId = 0;
    /**
     * Set the page format of the current page.
     *
     * @param array $size An array with two values defining the size.
     * @param string $orientation "L" for landscape, "P" for portrait.
     * @throws \BadMethodCallException
     */
    public function setPageFormat($size, $orientation)
    {
    }
    /**
     * Draws a template onto the page or another template.
     *
     * Give only one of the size parameters (width, height) to calculate the other one automatically in view to the
     * aspect ratio.
     *
     * @param mixed $tpl The template id
     * @param array|float|int $x The abscissa of upper-left corner. Alternatively you could use an assoc array
     *                           with the keys "x", "y", "width", "height", "adjustPageSize".
     * @param float|int $y The ordinate of upper-left corner.
     * @param float|int|null $width The width.
     * @param float|int|null $height The height.
     * @param bool $adjustPageSize
     * @return array The size
     * @see FpdfTplTrait::getTemplateSize()
     */
    public function useTemplate($tpl, $x = 0, $y = 0, $width = null, $height = null, $adjustPageSize = false)
    {
    }
    /**
     * Get the size of a template.
     *
     * Give only one of the size parameters (width, height) to calculate the other one automatically in view to the
     * aspect ratio.
     *
     * @param mixed $tpl The template id
     * @param float|int|null $width The width.
     * @param float|int|null $height The height.
     * @return array|bool An array with following keys: width, height, 0 (=width), 1 (=height), orientation (L or P)
     */
    public function getTemplateSize($tpl, $width = null, $height = null)
    {
    }
    /**
     * Begins a new template.
     *
     * @param float|int|null $width The width of the template. If null, the current page width is used.
     * @param float|int|null $height The height of the template. If null, the current page height is used.
     * @param bool $groupXObject Define the form XObject as a group XObject to support transparency (if used).
     * @return int A template identifier.
     */
    public function beginTemplate($width = null, $height = null, $groupXObject = false)
    {
    }
    /**
     * Ends a template.
     *
     * @return bool|int|null A template identifier.
     */
    public function endTemplate()
    {
    }
    /**
     * Get the next template id.
     *
     * @return int
     */
    protected function getNextTemplateId()
    {
    }
    /* overwritten FPDF methods: */
    /**
     * @inheritdoc
     */
    public function AddPage($orientation = '', $size = '', $rotation = 0)
    {
    }
    /**
     * @inheritdoc
     */
    public function Link($x, $y, $w, $h, $link)
    {
    }
    /**
     * @inheritdoc
     */
    public function SetLink($link, $y = 0, $page = -1)
    {
    }
    /**
     * @inheritdoc
     */
    public function SetDrawColor($r, $g = null, $b = null)
    {
    }
    /**
     * @inheritdoc
     */
    public function SetFillColor($r, $g = null, $b = null)
    {
    }
    /**
     * @inheritdoc
     */
    public function SetLineWidth($width)
    {
    }
    /**
     * @inheritdoc
     */
    public function SetFont($family, $style = '', $size = 0)
    {
    }
    /**
     * @inheritdoc
     */
    public function SetFontSize($size)
    {
    }
    protected function _putimages()
    {
    }
    /**
     * @inheritdoc
     */
    protected function _putxobjectdict()
    {
    }
    /**
     * @inheritdoc
     */
    public function _out($s)
    {
    }
}