<?php

/**
 * Auto-generated stub file for Moodle's public/lib/openspout/src/Writer/CSV/Options.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
namespace OpenSpout\Writer\CSV;

final class Options
{
    public string $FIELD_DELIMITER = ',';
    public string $FIELD_ENCLOSURE = '"';
    public bool $SHOULD_ADD_BOM = true;
    /** @var positive-int */
    public int $FLUSH_THRESHOLD = 500;
}