<?php

/**
 * Auto-generated stub file for Moodle's public/mod/assign/feedback/editpdf/backup/moodle2/restore_assignfeedback_editpdf_subplugin.class.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/**
 * Restore subplugin class.
 *
 * Provides the necessary information needed
 * to restore one assign_feedback subplugin.
 *
 * @package   assignfeedback_editpdf
 * @copyright 2013 Damyon Wiese
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class restore_assignfeedback_editpdf_subplugin extends restore_subplugin
{
    /**
     * Returns the paths to be handled by the subplugin at assignment level
     * @return array
     */
    protected function define_grade_subplugin_structure()
    {
    }
    /**
     * Processes one feedback_editpdf_files element
     * @param mixed $data
     */
    public function process_assignfeedback_editpdf_files($data)
    {
    }
    /**
     * Processes one feedback_editpdf_annotations/annotation element
     * @param mixed $data
     */
    public function process_assignfeedback_editpdf_annotation($data)
    {
    }
    /**
     * Processes one feedback_editpdf_comments/comment element
     * @param mixed $data
     */
    public function process_assignfeedback_editpdf_comment($data)
    {
    }
    /**
     * Processes one /feedback_editpdf_rotation/pagerotation element
     * @param mixed $data
     */
    public function process_assignfeedback_editpdf_pagerotation($data)
    {
    }
}