<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Connectors/Connector.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Connectors;

class Connector extends \Google\Model
{
    /**
     * @var string
     */
    public $createTime;
    /**
     * @var string
     */
    public $description;
    /**
     * @var string
     */
    public $displayName;
    /**
     * @var string
     */
    public $documentationUri;
    /**
     * @var string
     */
    public $externalUri;
    /**
     * @var string[]
     */
    public $labels;
    /**
     * @var string
     */
    public $launchStage;
    /**
     * @var string
     */
    public $name;
    /**
     * @var string
     */
    public $updateTime;
    /**
     * @var string
     */
    public $webAssetsLocation;
    /**
     * @param string
     */
    public function setCreateTime($createTime)
    {
    }
    /**
     * @return string
     */
    public function getCreateTime()
    {
    }
    /**
     * @param string
     */
    public function setDescription($description)
    {
    }
    /**
     * @return string
     */
    public function getDescription()
    {
    }
    /**
     * @param string
     */
    public function setDisplayName($displayName)
    {
    }
    /**
     * @return string
     */
    public function getDisplayName()
    {
    }
    /**
     * @param string
     */
    public function setDocumentationUri($documentationUri)
    {
    }
    /**
     * @return string
     */
    public function getDocumentationUri()
    {
    }
    /**
     * @param string
     */
    public function setExternalUri($externalUri)
    {
    }
    /**
     * @return string
     */
    public function getExternalUri()
    {
    }
    /**
     * @param string[]
     */
    public function setLabels($labels)
    {
    }
    /**
     * @return string[]
     */
    public function getLabels()
    {
    }
    /**
     * @param string
     */
    public function setLaunchStage($launchStage)
    {
    }
    /**
     * @return string
     */
    public function getLaunchStage()
    {
    }
    /**
     * @param string
     */
    public function setName($name)
    {
    }
    /**
     * @return string
     */
    public function getName()
    {
    }
    /**
     * @param string
     */
    public function setUpdateTime($updateTime)
    {
    }
    /**
     * @return string
     */
    public function getUpdateTime()
    {
    }
    /**
     * @param string
     */
    public function setWebAssetsLocation($webAssetsLocation)
    {
    }
    /**
     * @return string
     */
    public function getWebAssetsLocation()
    {
    }
}