<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Dialogflow/GoogleCloudDialogflowV2IntentMessageMediaContentResponseMediaObject.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Dialogflow {
    class GoogleCloudDialogflowV2IntentMessageMediaContentResponseMediaObject extends \Google\Model
    {
        /**
         * @var string
         */
        public $contentUrl;
        /**
         * @var string
         */
        public $description;
        protected $iconType = GoogleCloudDialogflowV2IntentMessageImage::class;
        protected $iconDataType = '';
        protected $largeImageType = GoogleCloudDialogflowV2IntentMessageImage::class;
        protected $largeImageDataType = '';
        /**
         * @var string
         */
        public $name;
        /**
         * @param string $contentUrl
         */
        public function setContentUrl($contentUrl)
        {
        }
        /**
         * @return string
         */
        public function getContentUrl()
        {
        }
        /**
         * @param string $description
         */
        public function setDescription($description)
        {
        }
        /**
         * @return string
         */
        public function getDescription()
        {
        }
        /**
         * @param GoogleCloudDialogflowV2IntentMessageImage $icon
         */
        public function setIcon(GoogleCloudDialogflowV2IntentMessageImage $icon)
        {
        }
        /**
         * @return GoogleCloudDialogflowV2IntentMessageImage
         */
        public function getIcon()
        {
        }
        /**
         * @param GoogleCloudDialogflowV2IntentMessageImage $largeImage
         */
        public function setLargeImage(GoogleCloudDialogflowV2IntentMessageImage $largeImage)
        {
        }
        /**
         * @return GoogleCloudDialogflowV2IntentMessageImage
         */
        public function getLargeImage()
        {
        }
        /**
         * @param string $name
         */
        public function setName($name)
        {
        }
        /**
         * @return string
         */
        public function getName()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\Dialogflow\GoogleCloudDialogflowV2IntentMessageMediaContentResponseMediaObject registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_Dialogflow_GoogleCloudDialogflowV2IntentMessageMediaContentResponseMediaObject extends \Google\Service\Dialogflow\GoogleCloudDialogflowV2IntentMessageMediaContentResponseMediaObject
    {
    }
}