<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Dialogflow/GoogleCloudDialogflowV2KnowledgeAssistAnswer.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Dialogflow {
    class GoogleCloudDialogflowV2KnowledgeAssistAnswer extends \Google\Model
    {
        /**
         * The name of the answer record. Format: `projects//locations//answer
         * Records/`.
         *
         * @var string
         */
        public $answerRecord;
        protected $suggestedQueryType = GoogleCloudDialogflowV2KnowledgeAssistAnswerSuggestedQuery::class;
        protected $suggestedQueryDataType = '';
        protected $suggestedQueryAnswerType = GoogleCloudDialogflowV2KnowledgeAssistAnswerKnowledgeAnswer::class;
        protected $suggestedQueryAnswerDataType = '';
        /**
         * The name of the answer record. Format: `projects//locations//answer
         * Records/`.
         *
         * @param string $answerRecord
         */
        public function setAnswerRecord($answerRecord)
        {
        }
        /**
         * @return string
         */
        public function getAnswerRecord()
        {
        }
        /**
         * The query suggested based on the context. Suggestion is made only if it is
         * different from the previous suggestion.
         *
         * @param GoogleCloudDialogflowV2KnowledgeAssistAnswerSuggestedQuery $suggestedQuery
         */
        public function setSuggestedQuery(GoogleCloudDialogflowV2KnowledgeAssistAnswerSuggestedQuery $suggestedQuery)
        {
        }
        /**
         * @return GoogleCloudDialogflowV2KnowledgeAssistAnswerSuggestedQuery
         */
        public function getSuggestedQuery()
        {
        }
        /**
         * The answer generated for the suggested query. Whether or not an answer is
         * generated depends on how confident we are about the generated query.
         *
         * @param GoogleCloudDialogflowV2KnowledgeAssistAnswerKnowledgeAnswer $suggestedQueryAnswer
         */
        public function setSuggestedQueryAnswer(GoogleCloudDialogflowV2KnowledgeAssistAnswerKnowledgeAnswer $suggestedQueryAnswer)
        {
        }
        /**
         * @return GoogleCloudDialogflowV2KnowledgeAssistAnswerKnowledgeAnswer
         */
        public function getSuggestedQueryAnswer()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\Dialogflow\GoogleCloudDialogflowV2KnowledgeAssistAnswer registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_Dialogflow_GoogleCloudDialogflowV2KnowledgeAssistAnswer extends \Google\Service\Dialogflow\GoogleCloudDialogflowV2KnowledgeAssistAnswer
    {
    }
}