<?php

/**
 * Auto-generated stub file for Moodle's public/lib/classes/reportbuilder/local/systemreports/api_tokens.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
namespace core\reportbuilder\local\systemreports;

use core\api\entity\api_token_entity;
use core\reportbuilder\local\entities\api_token;
use core\url;
use core_reportbuilder\output\report_action;
use core_reportbuilder\system_report;
use lang_string;
/**
 * Lists the personal access tokens belonging to the current user.
 *
 * @package    core
 * @copyright  Meirza Arson <meirza.arson@moodle.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class api_tokens extends system_report
{
    #[\Override]
    protected function initialise(): void
    {
    }
    /**
     * Only the owner of the tokens may see them, and only where tokens are theirs to create.
     *
     * @return bool
     */
    #[\Override]
    protected function can_view(): bool
    {
    }
}