<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Datastore/GoogleDatastoreAdminV1beta1ImportEntitiesMetadata.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Datastore;

class GoogleDatastoreAdminV1beta1ImportEntitiesMetadata extends \Google\Model
{
    protected $commonType = GoogleDatastoreAdminV1beta1CommonMetadata::class;
    protected $commonDataType = '';
    protected $entityFilterType = GoogleDatastoreAdminV1beta1EntityFilter::class;
    protected $entityFilterDataType = '';
    /**
     * The location of the import metadata file. This will be the same value as
     * the google.datastore.admin.v1beta1.ExportEntitiesResponse.output_url field.
     *
     * @var string
     */
    public $inputUrl;
    protected $progressBytesType = GoogleDatastoreAdminV1beta1Progress::class;
    protected $progressBytesDataType = '';
    protected $progressEntitiesType = GoogleDatastoreAdminV1beta1Progress::class;
    protected $progressEntitiesDataType = '';
    /**
     * Metadata common to all Datastore Admin operations.
     *
     * @param GoogleDatastoreAdminV1beta1CommonMetadata $common
     */
    public function setCommon(GoogleDatastoreAdminV1beta1CommonMetadata $common)
    {
    }
    /**
     * @return GoogleDatastoreAdminV1beta1CommonMetadata
     */
    public function getCommon()
    {
    }
    /**
     * Description of which entities are being imported.
     *
     * @param GoogleDatastoreAdminV1beta1EntityFilter $entityFilter
     */
    public function setEntityFilter(GoogleDatastoreAdminV1beta1EntityFilter $entityFilter)
    {
    }
    /**
     * @return GoogleDatastoreAdminV1beta1EntityFilter
     */
    public function getEntityFilter()
    {
    }
    /**
     * The location of the import metadata file. This will be the same value as
     * the google.datastore.admin.v1beta1.ExportEntitiesResponse.output_url field.
     *
     * @param string $inputUrl
     */
    public function setInputUrl($inputUrl)
    {
    }
    /**
     * @return string
     */
    public function getInputUrl()
    {
    }
    /**
     * An estimate of the number of bytes processed.
     *
     * @param GoogleDatastoreAdminV1beta1Progress $progressBytes
     */
    public function setProgressBytes(GoogleDatastoreAdminV1beta1Progress $progressBytes)
    {
    }
    /**
     * @return GoogleDatastoreAdminV1beta1Progress
     */
    public function getProgressBytes()
    {
    }
    /**
     * An estimate of the number of entities processed.
     *
     * @param GoogleDatastoreAdminV1beta1Progress $progressEntities
     */
    public function setProgressEntities(GoogleDatastoreAdminV1beta1Progress $progressEntities)
    {
    }
    /**
     * @return GoogleDatastoreAdminV1beta1Progress
     */
    public function getProgressEntities()
    {
    }
}