<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/CloudHealthcare/PubsubDestination.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\CloudHealthcare {
    class PubsubDestination extends \Google\Model
    {
        /**
         * The [Pub/Sub](https://cloud.google.com/pubsub/docs/) topic that Pub/Sub
         * messages are published on. Supplied by the client. The `PubsubMessage`
         * contains the following fields: * `PubsubMessage.Data` contains the resource
         * name. * `PubsubMessage.MessageId` is the ID of this notification. It is
         * guaranteed to be unique within the topic. * `PubsubMessage.PublishTime` is
         * the time when the message was published. [Topic
         * names](https://cloud.google.com/pubsub/docs/overview#names) must be scoped
         * to a project. The Cloud Healthcare API service account, service-
         * PROJECT_NUMBER@gcp-sa-healthcare.iam.gserviceaccount.com, must have
         * publisher permissions on the given Pub/Sub topic. Not having adequate
         * permissions causes the calls that send notifications to fail.
         *
         * @var string
         */
        public $pubsubTopic;
        /**
         * The [Pub/Sub](https://cloud.google.com/pubsub/docs/) topic that Pub/Sub
         * messages are published on. Supplied by the client. The `PubsubMessage`
         * contains the following fields: * `PubsubMessage.Data` contains the resource
         * name. * `PubsubMessage.MessageId` is the ID of this notification. It is
         * guaranteed to be unique within the topic. * `PubsubMessage.PublishTime` is
         * the time when the message was published. [Topic
         * names](https://cloud.google.com/pubsub/docs/overview#names) must be scoped
         * to a project. The Cloud Healthcare API service account, service-
         * PROJECT_NUMBER@gcp-sa-healthcare.iam.gserviceaccount.com, must have
         * publisher permissions on the given Pub/Sub topic. Not having adequate
         * permissions causes the calls that send notifications to fail.
         *
         * @param string $pubsubTopic
         */
        public function setPubsubTopic($pubsubTopic)
        {
        }
        /**
         * @return string
         */
        public function getPubsubTopic()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\CloudHealthcare\PubsubDestination registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_CloudHealthcare_PubsubDestination extends \Google\Service\CloudHealthcare\PubsubDestination
    {
    }
}