<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Dataflow/SourceFork.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Dataflow;

class SourceFork extends \Google\Model
{
    protected $primaryType = SourceSplitShard::class;
    protected $primaryDataType = '';
    protected $primarySourceType = DerivedSource::class;
    protected $primarySourceDataType = '';
    protected $residualType = SourceSplitShard::class;
    protected $residualDataType = '';
    protected $residualSourceType = DerivedSource::class;
    protected $residualSourceDataType = '';
    /**
     * DEPRECATED
     *
     * @param SourceSplitShard $primary
     */
    public function setPrimary(SourceSplitShard $primary)
    {
    }
    /**
     * @return SourceSplitShard
     */
    public function getPrimary()
    {
    }
    /**
     * DEPRECATED
     *
     * @param DerivedSource $primarySource
     */
    public function setPrimarySource(DerivedSource $primarySource)
    {
    }
    /**
     * @return DerivedSource
     */
    public function getPrimarySource()
    {
    }
    /**
     * DEPRECATED
     *
     * @param SourceSplitShard $residual
     */
    public function setResidual(SourceSplitShard $residual)
    {
    }
    /**
     * @return SourceSplitShard
     */
    public function getResidual()
    {
    }
    /**
     * DEPRECATED
     *
     * @param DerivedSource $residualSource
     */
    public function setResidualSource(DerivedSource $residualSource)
    {
    }
    /**
     * @return DerivedSource
     */
    public function getResidualSource()
    {
    }
}