<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Speech/CreatePhraseSetRequest.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Speech {
    class CreatePhraseSetRequest extends \Google\Model
    {
        protected $phraseSetType = PhraseSet::class;
        protected $phraseSetDataType = '';
        /**
         * Required. The ID to use for the phrase set, which will become the final
         * component of the phrase set's resource name. This value should restrict to
         * letters, numbers, and hyphens, with the first character a letter, the last
         * a letter or a number, and be 4-63 characters.
         *
         * @var string
         */
        public $phraseSetId;
        /**
         * Required. The phrase set to create.
         *
         * @param PhraseSet $phraseSet
         */
        public function setPhraseSet(PhraseSet $phraseSet)
        {
        }
        /**
         * @return PhraseSet
         */
        public function getPhraseSet()
        {
        }
        /**
         * Required. The ID to use for the phrase set, which will become the final
         * component of the phrase set's resource name. This value should restrict to
         * letters, numbers, and hyphens, with the first character a letter, the last
         * a letter or a number, and be 4-63 characters.
         *
         * @param string $phraseSetId
         */
        public function setPhraseSetId($phraseSetId)
        {
        }
        /**
         * @return string
         */
        public function getPhraseSetId()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\Speech\CreatePhraseSetRequest registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_Speech_CreatePhraseSetRequest extends \Google\Service\Speech\CreatePhraseSetRequest
    {
    }
}