<?php

/**
 * Auto-generated stub file for Moodle's lib/phpexcel/PHPExcel/Reader/Excel2007/Chart.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/**
 * PHPExcel
 *
 * Copyright (c) 2006 - 2015 PHPExcel
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * @category    PHPExcel
 * @package        PHPExcel_Reader_Excel2007
 * @copyright    Copyright (c) 2006 - 2015 PHPExcel (http://www.codeplex.com/PHPExcel)
 * @license        http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt    LGPL
 * @version        ##VERSION##, ##DATE##
 */
/**
 * PHPExcel_Reader_Excel2007_Chart
 *
 * @category    PHPExcel
 * @package        PHPExcel_Reader_Excel2007
 * @copyright    Copyright (c) 2006 - 2015 PHPExcel (http://www.codeplex.com/PHPExcel)
 */
class PHPExcel_Reader_Excel2007_Chart
{
    private static function getAttribute($component, $name, $format)
    {
    }
    private static function readColor($color, $background = false)
    {
    }
    public static function readChart($chartElements, $chartName)
    {
    }
    private static function chartTitle($titleDetails, $namespacesChartMeta, $type)
    {
    }
    private static function chartLayoutDetails($chartDetail, $namespacesChartMeta)
    {
    }
    private static function chartDataSeries($chartDetail, $namespacesChartMeta, $plotType)
    {
    }
    private static function chartDataSeriesValueSet($seriesDetail, $namespacesChartMeta, $marker = null, $smoothLine = false)
    {
    }
    private static function chartDataSeriesValues($seriesValueSet, $dataType = 'n')
    {
    }
    private static function chartDataSeriesValuesMultiLevel($seriesValueSet, $dataType = 'n')
    {
    }
    private static function parseRichText($titleDetailPart = null)
    {
    }
    private static function readChartAttributes($chartDetail)
    {
    }
    private static function setChartAttributes($plotArea, $plotAttributes)
    {
    }
}