<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Eventarc/MessageBus.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Eventarc {
    class MessageBus extends \Google\Model
    {
        /**
         * Optional. Resource annotations.
         *
         * @var string[]
         */
        public $annotations;
        /**
         * Output only. The creation time.
         *
         * @var string
         */
        public $createTime;
        /**
         * Optional. Resource name of a KMS crypto key (managed by the user) used to
         * encrypt/decrypt their event data. It must match the pattern
         * `projects/locations/keyRings/cryptoKeys`.
         *
         * @var string
         */
        public $cryptoKeyName;
        /**
         * Optional. Resource display name.
         *
         * @var string
         */
        public $displayName;
        /**
         * Output only. This checksum is computed by the server based on the value of
         * other fields, and might be sent only on update and delete requests to
         * ensure that the client has an up-to-date value before proceeding.
         *
         * @var string
         */
        public $etag;
        /**
         * Optional. Resource labels.
         *
         * @var string[]
         */
        public $labels;
        protected $loggingConfigType = LoggingConfig::class;
        protected $loggingConfigDataType = '';
        /**
         * Identifier. Resource name of the form
         * projects/{project}/locations/{location}/messageBuses/{message_bus}
         *
         * @var string
         */
        public $name;
        /**
         * Output only. Server assigned unique identifier for the channel. The value
         * is a UUID4 string and guaranteed to remain unchanged until the resource is
         * deleted.
         *
         * @var string
         */
        public $uid;
        /**
         * Output only. The last-modified time.
         *
         * @var string
         */
        public $updateTime;
        /**
         * Optional. Resource annotations.
         *
         * @param string[] $annotations
         */
        public function setAnnotations($annotations)
        {
        }
        /**
         * @return string[]
         */
        public function getAnnotations()
        {
        }
        /**
         * Output only. The creation time.
         *
         * @param string $createTime
         */
        public function setCreateTime($createTime)
        {
        }
        /**
         * @return string
         */
        public function getCreateTime()
        {
        }
        /**
         * Optional. Resource name of a KMS crypto key (managed by the user) used to
         * encrypt/decrypt their event data. It must match the pattern
         * `projects/locations/keyRings/cryptoKeys`.
         *
         * @param string $cryptoKeyName
         */
        public function setCryptoKeyName($cryptoKeyName)
        {
        }
        /**
         * @return string
         */
        public function getCryptoKeyName()
        {
        }
        /**
         * Optional. Resource display name.
         *
         * @param string $displayName
         */
        public function setDisplayName($displayName)
        {
        }
        /**
         * @return string
         */
        public function getDisplayName()
        {
        }
        /**
         * Output only. This checksum is computed by the server based on the value of
         * other fields, and might be sent only on update and delete requests to
         * ensure that the client has an up-to-date value before proceeding.
         *
         * @param string $etag
         */
        public function setEtag($etag)
        {
        }
        /**
         * @return string
         */
        public function getEtag()
        {
        }
        /**
         * Optional. Resource labels.
         *
         * @param string[] $labels
         */
        public function setLabels($labels)
        {
        }
        /**
         * @return string[]
         */
        public function getLabels()
        {
        }
        /**
         * Optional. Config to control Platform logging for the Message Bus. This log
         * configuration is applied to the Message Bus itself, and all the Enrollments
         * attached to it.
         *
         * @param LoggingConfig $loggingConfig
         */
        public function setLoggingConfig(LoggingConfig $loggingConfig)
        {
        }
        /**
         * @return LoggingConfig
         */
        public function getLoggingConfig()
        {
        }
        /**
         * Identifier. Resource name of the form
         * projects/{project}/locations/{location}/messageBuses/{message_bus}
         *
         * @param string $name
         */
        public function setName($name)
        {
        }
        /**
         * @return string
         */
        public function getName()
        {
        }
        /**
         * Output only. Server assigned unique identifier for the channel. The value
         * is a UUID4 string and guaranteed to remain unchanged until the resource is
         * deleted.
         *
         * @param string $uid
         */
        public function setUid($uid)
        {
        }
        /**
         * @return string
         */
        public function getUid()
        {
        }
        /**
         * Output only. The last-modified time.
         *
         * @param string $updateTime
         */
        public function setUpdateTime($updateTime)
        {
        }
        /**
         * @return string
         */
        public function getUpdateTime()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\Eventarc\MessageBus registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_Eventarc_MessageBus extends \Google\Service\Eventarc\MessageBus
    {
    }
}