<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Apigee/GoogleCloudApigeeV1SecurityReportResultMetadata.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Apigee;

class GoogleCloudApigeeV1SecurityReportResultMetadata extends \Google\Model
{
    /**
     * Output only. Expire_time is set to 7 days after report creation. Query
     * result will be unaccessable after this time. Example:
     * "2021-05-04T13:38:52-07:00"
     *
     * @var string
     */
    public $expires;
    /**
     * Self link of the query results. Example: `/organizations/myorg/environments
     * /myenv/securityReports/9cfc0d85-0f30-46d6-ae6f-318d0cb961bd/result` or
     * following format if query is running at host level: `/organizations/myorg/h
     * ostSecurityReports/9cfc0d85-0f30-46d6-ae6f-318d0cb961bd/result`
     *
     * @var string
     */
    public $self;
    /**
     * Output only. Expire_time is set to 7 days after report creation. Query
     * result will be unaccessable after this time. Example:
     * "2021-05-04T13:38:52-07:00"
     *
     * @param string $expires
     */
    public function setExpires($expires)
    {
    }
    /**
     * @return string
     */
    public function getExpires()
    {
    }
    /**
     * Self link of the query results. Example: `/organizations/myorg/environments
     * /myenv/securityReports/9cfc0d85-0f30-46d6-ae6f-318d0cb961bd/result` or
     * following format if query is running at host level: `/organizations/myorg/h
     * ostSecurityReports/9cfc0d85-0f30-46d6-ae6f-318d0cb961bd/result`
     *
     * @param string $self
     */
    public function setSelf($self)
    {
    }
    /**
     * @return string
     */
    public function getSelf()
    {
    }
}