<?php

/**
 * Auto-generated stub file for Moodle's mod/workshop/restorelib.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
//$Id$
//This php script contains all the stuff to backup/restore
//workshop mods
//This is the "graphical" structure of the workshop mod:
//
//                                          workshop
//                                         (CL,pk->id)
//                                             |
//                                             |
//                                             |
//              |------------------------------|-----------------------------------------------------|
//              |                                                                                    |
//              |                                                                                    |
//              |                                                                                    |
//              |                                                                            workshop_submissions
//              |                                                                        (UL,pk->id,fk->workshopid,files)
//              |                                                                                    |
//              |        |-------------------------------------|      |----------------------|       |
//              |        |                                     |      |                      |       |
//             workshop_elements                           workshop_grades                  workshop_assessments
//         (CL,pk->id,fk->workshopid)                (UL,pk->id,fk->assessmentid)       (UL,pk->id,fk->submissionid)
//              |                  |                 (          fk->elementno   )                    |
//              |                  |                                                                 |
//              |                  |                                                                 |
//      workshop_rubrics          workshop_stockcomments                                        workshop_comments
// (CL,pk->id,fk->elementno)   (CL, pk->id, fk->elementno)                             (UL,pk->id,fk->assessmentid)
//
// Meaning: pk->primary key field of the table
//          fk->foreign key to link with parent
//          nt->nested field (recursive data)
//          CL->course level info
//          UL->user level info
//          files->table may have files)
//
//-----------------------------------------------------------
//This function executes all the restore procedure about this mod
function workshop_restore_mods($mod, $restore)
{
}
//This function restores the workshop_elements
function workshop_elements_restore_mods($workshop_id, $info, $restore)
{
}
//This function restores the workshop_rubrics
function workshop_rubrics_restore_mods($workshop_id, $elementno, $info, $restore)
{
}
//This function restores the workshop_stockcomments
function workshop_stockcomments_restore_mods($new_workshop_id, $elementno, $info, $restore)
{
}
//This function restores the workshop_submissions
function workshop_submissions_restore_mods($old_workshop_id, $new_workshop_id, $info, $restore)
{
}
//This function restores the workshop_assessments       
function workshop_assessments_restore_mods($new_workshop_id, $new_submission_id, $info, $restore)
{
}
//This function restores the workshop_comments
function workshop_comments_restore_mods($new_workshop_id, $new_assessment_id, $info, $restore)
{
}
//This function restores the workshop_grades
function workshop_grades_restore_mods($new_workshop_id, $new_assessment_id, $info, $restore)
{
}
//This function copies the workshop related info from backup temp dir to course moddata folder,
//creating it if needed and recoding everything (submission_id) 
function workshop_restore_files($oldsubmiss, $newsubmiss, $restore)
{
}
//This function converts texts in FORMAT_WIKI to FORMAT_MARKDOWN for
//some texts in the module
function workshop_restore_wiki2markdown($restore)
{
}
//Return a content decoded to support interactivities linking. Every module
//should have its own. They are called automatically from
//workshop_decode_content_links_caller() function in each module
//in the restore process
function workshop_decode_content_links($content, $restore)
{
}
//This function makes all the necessary calls to xxxx_decode_content_links()
//function in each module, passing them the desired contents to be decoded
//from backup format to destination site/course in order to mantain inter-activities
//working in the backup/restore process. It's called from restore_decode_content_links()
//function in restore process
function workshop_decode_content_links_caller($restore)
{
}
//This function returns a log record with all the necessay transformations
//done. It's used by restore_log_module() to restore modules log.
function workshop_restore_logs($restore, $log)
{
}