<?php

/**
 * Auto-generated stub file for Moodle's lib/alfresco/Service/Repository.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
class Alfresco_Repository extends BaseObject
{
    private $_connectionUrl;
    private $_host;
    private $_port;
    public function __construct($connectionUrl = "http://localhost:8080/alfresco/api")
    {
    }
    public function getConnectionUrl()
    {
    }
    public function getHost()
    {
    }
    public function getPort()
    {
    }
    public function authenticate($userName, $password)
    {
    }
    public function createSession($ticket = null)
    {
    }
    /**
     * For a given ticket, returns the realated session id, null if one can not be found.
     */
    public static function getSessionId($ticket)
    {
    }
}