<?php

/**
 * Auto-generated stub file for Moodle's auth/pam/auth.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/**
 * PAM authentication plugin.
 */
class auth_plugin_pam extends auth_plugin_base
{
    /**
     * Store error messages from pam authentication attempts.
     */
    var $lasterror;
    /**
     * Constructor.
     */
    public function __construct()
    {
    }
    /**
     * Old syntax of class constructor. Deprecated in PHP7.
     *
     * @deprecated since Moodle 3.1
     */
    public function auth_plugin_pam()
    {
    }
    /**
     * Returns true if the username and password work and false if they are
     * wrong or don't exist.
     *
     * @param string $username The username
     * @param string $password The password
     * @return bool Authentication success or failure.
     */
    function user_login($username, $password)
    {
    }
    function prevent_local_passwords()
    {
    }
    /**
     * Returns true if this authentication plugin is 'internal'.
     *
     * @return bool
     */
    function is_internal()
    {
    }
    /**
     * Returns true if this authentication plugin can change the user's
     * password.
     *
     * @return bool
     */
    function can_change_password()
    {
    }
}