<?php

/**
 * Auto-generated stub file for Moodle's question/engine/simpletest/testquestionbank.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/**
 *Unit tests for the {@link question_bank} class.
 *
 * @copyright  2011 The Open University
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class question_bank_test extends UnitTestCase
{
    public function setUp()
    {
    }
    public function tearDown()
    {
    }
    public function test_sort_qtype_array()
    {
    }
    public function test_fraction_options()
    {
    }
    public function test_fraction_options_full()
    {
    }
}