<?php

/**
 * Auto-generated stub file for Moodle's lib/spout/src/Spout/Writer/Common/Sheet.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
namespace Box\Spout\Writer\Common;

/**
 * Class Sheet
 * External representation of a worksheet within a ODS file
 *
 * @package Box\Spout\Writer\Common
 */
class Sheet
{
    const DEFAULT_SHEET_NAME_PREFIX = 'Sheet';
    /** Sheet name should not exceed 31 characters */
    const MAX_LENGTH_SHEET_NAME = 31;
    /** @var array Invalid characters that cannot be contained in the sheet name */
    private static $INVALID_CHARACTERS_IN_SHEET_NAME = ['\\', '/', '?', '*', ':', '[', ']'];
    /** @var array Associative array [SHEET_INDEX] => [SHEET_NAME] keeping track of sheets' name to enforce uniqueness */
    protected static $SHEETS_NAME_USED = [];
    /** @var int Index of the sheet, based on order in the workbook (zero-based) */
    protected $index;
    /** @var string Name of the sheet */
    protected $name;
    /** @var \Box\Spout\Common\Helper\StringHelper */
    protected $stringHelper;
    /**
     * @param int $sheetIndex Index of the sheet, based on order in the workbook (zero-based)
     */
    public function __construct($sheetIndex)
    {
    }
    /**
     * @api
     * @return int Index of the sheet, based on order in the workbook (zero-based)
     */
    public function getIndex()
    {
    }
    /**
     * @api
     * @return string Name of the sheet
     */
    public function getName()
    {
    }
    /**
     * Sets the name of the sheet. Note that Excel has some restrictions on the name:
     *  - it should not be blank
     *  - it should not exceed 31 characters
     *  - it should not contain these characters: \ / ? * : [ or ]
     *  - it should be unique
     *
     * @api
     * @param string $name Name of the sheet
     * @return Sheet
     * @throws \Box\Spout\Writer\Exception\InvalidSheetNameException If the sheet's name is invalid.
     */
    public function setName($name)
    {
    }
    /**
     * Returns whether the given sheet's name is valid.
     * @see Sheet::setName for validity rules.
     *
     * @param string $name
     * @return bool TRUE if the name is valid, FALSE otherwise.
     */
    protected function isNameValid($name)
    {
    }
    /**
     * Returns whether the given name contains at least one invalid character.
     * @see Sheet::$INVALID_CHARACTERS_IN_SHEET_NAME for the full list.
     *
     * @param string $name
     * @return bool TRUE if the name contains invalid characters, FALSE otherwise.
     */
    protected function doesContainInvalidCharacters($name)
    {
    }
    /**
     * Returns whether the given name starts or ends with a single quote
     *
     * @param string $name
     * @return bool TRUE if the name starts or ends with a single quote, FALSE otherwise.
     */
    protected function doesStartOrEndWithSingleQuote($name)
    {
    }
    /**
     * Returns whether the given name is unique.
     *
     * @param string $name
     * @return bool TRUE if the name is unique, FALSE otherwise.
     */
    protected function isNameUnique($name)
    {
    }
}