<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Analytics/LinkedForeignAccount.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Analytics {
    class LinkedForeignAccount extends \Google\Model
    {
        /**
         * Account ID to which this linked foreign account belongs.
         *
         * @var string
         */
        public $accountId;
        /**
         * Boolean indicating whether this is eligible for search.
         *
         * @var bool
         */
        public $eligibleForSearch;
        /**
         * Entity ad account link ID.
         *
         * @var string
         */
        public $id;
        /**
         * Internal ID for the web property to which this linked foreign account
         * belongs.
         *
         * @var string
         */
        public $internalWebPropertyId;
        /**
         * Resource type for linked foreign account.
         *
         * @var string
         */
        public $kind;
        /**
         * The foreign account ID. For example the an Google Ads `linkedAccountId` has
         * the following format XXX-XXX-XXXX.
         *
         * @var string
         */
        public $linkedAccountId;
        /**
         * Remarketing audience ID to which this linked foreign account belongs.
         *
         * @var string
         */
        public $remarketingAudienceId;
        /**
         * The status of this foreign account link.
         *
         * @var string
         */
        public $status;
        /**
         * The type of the foreign account. For example, `ADWORDS_LINKS`, `DBM_LINKS`,
         * `MCC_LINKS` or `OPTIMIZE`.
         *
         * @var string
         */
        public $type;
        /**
         * Web property ID of the form UA-XXXXX-YY to which this linked foreign
         * account belongs.
         *
         * @var string
         */
        public $webPropertyId;
        /**
         * Account ID to which this linked foreign account belongs.
         *
         * @param string $accountId
         */
        public function setAccountId($accountId)
        {
        }
        /**
         * @return string
         */
        public function getAccountId()
        {
        }
        /**
         * Boolean indicating whether this is eligible for search.
         *
         * @param bool $eligibleForSearch
         */
        public function setEligibleForSearch($eligibleForSearch)
        {
        }
        /**
         * @return bool
         */
        public function getEligibleForSearch()
        {
        }
        /**
         * Entity ad account link ID.
         *
         * @param string $id
         */
        public function setId($id)
        {
        }
        /**
         * @return string
         */
        public function getId()
        {
        }
        /**
         * Internal ID for the web property to which this linked foreign account
         * belongs.
         *
         * @param string $internalWebPropertyId
         */
        public function setInternalWebPropertyId($internalWebPropertyId)
        {
        }
        /**
         * @return string
         */
        public function getInternalWebPropertyId()
        {
        }
        /**
         * Resource type for linked foreign account.
         *
         * @param string $kind
         */
        public function setKind($kind)
        {
        }
        /**
         * @return string
         */
        public function getKind()
        {
        }
        /**
         * The foreign account ID. For example the an Google Ads `linkedAccountId` has
         * the following format XXX-XXX-XXXX.
         *
         * @param string $linkedAccountId
         */
        public function setLinkedAccountId($linkedAccountId)
        {
        }
        /**
         * @return string
         */
        public function getLinkedAccountId()
        {
        }
        /**
         * Remarketing audience ID to which this linked foreign account belongs.
         *
         * @param string $remarketingAudienceId
         */
        public function setRemarketingAudienceId($remarketingAudienceId)
        {
        }
        /**
         * @return string
         */
        public function getRemarketingAudienceId()
        {
        }
        /**
         * The status of this foreign account link.
         *
         * @param string $status
         */
        public function setStatus($status)
        {
        }
        /**
         * @return string
         */
        public function getStatus()
        {
        }
        /**
         * The type of the foreign account. For example, `ADWORDS_LINKS`, `DBM_LINKS`,
         * `MCC_LINKS` or `OPTIMIZE`.
         *
         * @param string $type
         */
        public function setType($type)
        {
        }
        /**
         * @return string
         */
        public function getType()
        {
        }
        /**
         * Web property ID of the form UA-XXXXX-YY to which this linked foreign
         * account belongs.
         *
         * @param string $webPropertyId
         */
        public function setWebPropertyId($webPropertyId)
        {
        }
        /**
         * @return string
         */
        public function getWebPropertyId()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\Analytics\LinkedForeignAccount registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_Analytics_LinkedForeignAccount extends \Google\Service\Analytics\LinkedForeignAccount
    {
    }
}