<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/CustomerEngagementSuite/OmnichannelIntegrationConfig.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\CustomerEngagementSuite {
    class OmnichannelIntegrationConfig extends \Google\Model
    {
        protected $channelConfigsType = OmnichannelIntegrationConfigChannelConfig::class;
        protected $channelConfigsDataType = 'map';
        protected $routingConfigsType = OmnichannelIntegrationConfigRoutingConfig::class;
        protected $routingConfigsDataType = 'map';
        protected $subscriberConfigsType = OmnichannelIntegrationConfigSubscriberConfig::class;
        protected $subscriberConfigsDataType = 'map';
        /**
         * Optional. Various of configuration for handling App events.
         *
         * @param OmnichannelIntegrationConfigChannelConfig[] $channelConfigs
         */
        public function setChannelConfigs($channelConfigs)
        {
        }
        /**
         * @return OmnichannelIntegrationConfigChannelConfig[]
         */
        public function getChannelConfigs()
        {
        }
        /**
         * Optional. The key of routing_configs is a key of `app_configs`, value is a
         * `RoutingConfig`, which contains subscriber's key.
         *
         * @param OmnichannelIntegrationConfigRoutingConfig[] $routingConfigs
         */
        public function setRoutingConfigs($routingConfigs)
        {
        }
        /**
         * @return OmnichannelIntegrationConfigRoutingConfig[]
         */
        public function getRoutingConfigs()
        {
        }
        /**
         * Optional. Various of subscribers configs.
         *
         * @param OmnichannelIntegrationConfigSubscriberConfig[] $subscriberConfigs
         */
        public function setSubscriberConfigs($subscriberConfigs)
        {
        }
        /**
         * @return OmnichannelIntegrationConfigSubscriberConfig[]
         */
        public function getSubscriberConfigs()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\CustomerEngagementSuite\OmnichannelIntegrationConfig registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_CustomerEngagementSuite_OmnichannelIntegrationConfig extends \Google\Service\CustomerEngagementSuite\OmnichannelIntegrationConfig
    {
    }
}