<?php

/**
 * Auto-generated stub file for Moodle's public/lib/htmlpurifier/HTMLPurifier/HTMLModule/CommonAttributes.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
class HTMLPurifier_HTMLModule_CommonAttributes extends HTMLPurifier_HTMLModule
{
    /**
     * @type string
     */
    public $name = 'CommonAttributes';
    /**
     * @type array
     */
    public $attr_collections = array('Core' => array(
        0 => array('Style'),
        // 'xml:space' => false,
        'class' => 'Class',
        'id' => 'ID',
        'title' => 'CDATA',
        'contenteditable' => 'ContentEditable',
    ), 'Lang' => array(), 'I18N' => array(0 => array('Lang')), 'Common' => array(0 => array('Core', 'I18N')));
}