<?php

/**
 * Auto-generated stub file for Moodle's lib/phpspreadsheet/phpspreadsheet/src/PhpSpreadsheet/Reader/Xlsx/TableReader.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
namespace PhpOffice\PhpSpreadsheet\Reader\Xlsx;

use PhpOffice\PhpSpreadsheet\Worksheet\Table;
use PhpOffice\PhpSpreadsheet\Worksheet\Table\TableStyle;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;
use SimpleXMLElement;
class TableReader
{
    /**
     * @var Worksheet
     */
    private $worksheet;
    /**
     * @var SimpleXMLElement
     */
    private $tableXml;
    public function __construct(Worksheet $workSheet, SimpleXMLElement $tableXml)
    {
    }
    /**
     * Loads Table into the Worksheet.
     */
    public function load(): void
    {
    }
    /**
     * Read Table from xml.
     */
    private function readTable(string $tableRange, SimpleXMLElement $tableXml): void
    {
    }
    /**
     * Reads TableAutoFilter from xml.
     */
    private function readTableAutoFilter(Table $table, SimpleXMLElement $autoFilterXml): void
    {
    }
    /**
     * Reads TableColumns from xml.
     */
    private function readTableColumns(Table $table, SimpleXMLElement $tableColumnsXml): void
    {
    }
    /**
     * Reads TableStyle from xml.
     */
    private function readTableStyle(Table $table, SimpleXMLElement $tableStyleInfoXml): void
    {
    }
}