<?php

/**
 * Auto-generated stub file for Moodle's cache/stores/mongodb/MongoDB/GridFS/StreamWrapper.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2016-present MongoDB, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace MongoDB\GridFS;

/**
 * Stream wrapper for reading and writing a GridFS file.
 *
 * @internal
 * @see Bucket::openUploadStream()
 * @see Bucket::openDownloadStream()
 */
class StreamWrapper
{
    /** @var resource|null Stream context (set by PHP) */
    public $context;
    /** @var string|null */
    private $mode;
    /** @var string|null */
    private $protocol;
    /** @var ReadableStream|WritableStream|null */
    private $stream;
    public function __destruct()
    {
    }
    /**
     * Return the stream's file document.
     */
    public function getFile(): object
    {
    }
    /**
     * Register the GridFS stream wrapper.
     *
     * @param string $protocol Protocol to use for stream_wrapper_register()
     */
    public static function register(string $protocol = 'gridfs'): void
    {
    }
    /**
     * Closes the stream.
     *
     * @see https://php.net/manual/en/streamwrapper.stream-close.php
     */
    public function stream_close(): void
    {
    }
    /**
     * Returns whether the file pointer is at the end of the stream.
     *
     * @see https://php.net/manual/en/streamwrapper.stream-eof.php
     */
    public function stream_eof(): bool
    {
    }
    /**
     * Opens the stream.
     *
     * @see https://php.net/manual/en/streamwrapper.stream-open.php
     * @param string      $path       Path to the file resource
     * @param string      $mode       Mode used to open the file (only "r" and "w" are supported)
     * @param integer     $options    Additional flags set by the streams API
     * @param string|null $openedPath Not used
     */
    public function stream_open(string $path, string $mode, int $options, ?string &$openedPath): bool
    {
    }
    /**
     * Read bytes from the stream.
     *
     * Note: this method may return a string smaller than the requested length
     * if data is not available to be read.
     *
     * @see https://php.net/manual/en/streamwrapper.stream-read.php
     * @param integer $length Number of bytes to read
     */
    public function stream_read(int $length): string
    {
    }
    /**
     * Return the current position of the stream.
     *
     * @see https://php.net/manual/en/streamwrapper.stream-seek.php
     * @param integer $offset Stream offset to seek to
     * @param integer $whence One of SEEK_SET, SEEK_CUR, or SEEK_END
     * @return boolean True if the position was updated and false otherwise
     */
    public function stream_seek(int $offset, int $whence = SEEK_SET): bool
    {
    }
    /**
     * Return information about the stream.
     *
     * @see https://php.net/manual/en/streamwrapper.stream-stat.php
     */
    public function stream_stat(): array
    {
    }
    /**
     * Return the current position of the stream.
     *
     * @see https://php.net/manual/en/streamwrapper.stream-tell.php
     * @return integer The current position of the stream
     */
    public function stream_tell(): int
    {
    }
    /**
     * Write bytes to the stream.
     *
     * @see https://php.net/manual/en/streamwrapper.stream-write.php
     * @param string $data Data to write
     * @return integer The number of bytes written
     */
    public function stream_write(string $data): int
    {
    }
    /**
     * Returns a stat template with default values.
     */
    private function getStatTemplate(): array
    {
    }
    /**
     * Initialize the protocol from the given path.
     *
     * @see StreamWrapper::stream_open()
     */
    private function initProtocol(string $path): void
    {
    }
    /**
     * Initialize the internal stream for reading.
     *
     * @see StreamWrapper::stream_open()
     */
    private function initReadableStream(): bool
    {
    }
    /**
     * Initialize the internal stream for writing.
     *
     * @see StreamWrapper::stream_open()
     */
    private function initWritableStream(): bool
    {
    }
}