<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Books/SeriesSeries.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Books;

class SeriesSeries extends \Google\Model
{
    /**
     * @var string
     */
    public $bannerImageUrl;
    /**
     * @var bool
     */
    public $eligibleForSubscription;
    /**
     * @var string
     */
    public $imageUrl;
    /**
     * @var bool
     */
    public $isComplete;
    /**
     * @var string
     */
    public $seriesFormatType;
    /**
     * @var string
     */
    public $seriesId;
    protected $seriesSubscriptionReleaseInfoType = SeriesSeriesSeriesSubscriptionReleaseInfo::class;
    protected $seriesSubscriptionReleaseInfoDataType = '';
    /**
     * @var string
     */
    public $seriesType;
    /**
     * @var string
     */
    public $subscriptionId;
    /**
     * @var string
     */
    public $title;
    /**
     * @param string $bannerImageUrl
     */
    public function setBannerImageUrl($bannerImageUrl)
    {
    }
    /**
     * @return string
     */
    public function getBannerImageUrl()
    {
    }
    /**
     * @param bool $eligibleForSubscription
     */
    public function setEligibleForSubscription($eligibleForSubscription)
    {
    }
    /**
     * @return bool
     */
    public function getEligibleForSubscription()
    {
    }
    /**
     * @param string $imageUrl
     */
    public function setImageUrl($imageUrl)
    {
    }
    /**
     * @return string
     */
    public function getImageUrl()
    {
    }
    /**
     * @param bool $isComplete
     */
    public function setIsComplete($isComplete)
    {
    }
    /**
     * @return bool
     */
    public function getIsComplete()
    {
    }
    /**
     * @param string $seriesFormatType
     */
    public function setSeriesFormatType($seriesFormatType)
    {
    }
    /**
     * @return string
     */
    public function getSeriesFormatType()
    {
    }
    /**
     * @param string $seriesId
     */
    public function setSeriesId($seriesId)
    {
    }
    /**
     * @return string
     */
    public function getSeriesId()
    {
    }
    /**
     * @param SeriesSeriesSeriesSubscriptionReleaseInfo $seriesSubscriptionReleaseInfo
     */
    public function setSeriesSubscriptionReleaseInfo(SeriesSeriesSeriesSubscriptionReleaseInfo $seriesSubscriptionReleaseInfo)
    {
    }
    /**
     * @return SeriesSeriesSeriesSubscriptionReleaseInfo
     */
    public function getSeriesSubscriptionReleaseInfo()
    {
    }
    /**
     * @param string $seriesType
     */
    public function setSeriesType($seriesType)
    {
    }
    /**
     * @return string
     */
    public function getSeriesType()
    {
    }
    /**
     * @param string $subscriptionId
     */
    public function setSubscriptionId($subscriptionId)
    {
    }
    /**
     * @return string
     */
    public function getSubscriptionId()
    {
    }
    /**
     * @param string $title
     */
    public function setTitle($title)
    {
    }
    /**
     * @return string
     */
    public function getTitle()
    {
    }
}