<?php

/**
 * Auto-generated stub file for Moodle's mod/scorm/datamodels/sequencinglib.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
function scorm_seq_exit_action_rules($seq, $userid)
{
}
function scorm_seq_post_cond_rules($seq, $userid)
{
}
function scorm_seq_evaluate_rollupcond($sco, $conditioncombination, $rollupruleconds, $userid)
{
}
function scorm_seq_check_child($sco, $action, $userid)
{
}
function scorm_seq_sequencing($scoid, $userid, $seq)
{
}
function scorm_seq_start_sequencing($scoid, $userid, $seq)
{
}
function scorm_seq_resume_all_sequencing($scoid, $userid, $seq)
{
}
function scorm_seq_continue_sequencing($scoid, $userid, $seq)
{
}
function scorm_seq_previous_sequencing($scoid, $userid, $seq)
{
}
function scorm_seq_exit_sequencing($scoid, $userid, $seq)
{
}
function scorm_seq_retry_sequencing($scoid, $userid, $seq)
{
}
function scorm_seq_choice_sequencing($sco, $userid, $seq)
{
}
function scorm_seq_choice_flow($constrained, $traverse, $seq)
{
}
function scorm_seq_choice_flow_tree($constrained, $traverse, $seq)
{
}
function scorm_seq_choice_activity_traversal($activity, $userid, $seq, $direction)
{
}
//Delivery Request Process
function scorm_sequencing_delivery($scoid, $userid, $seq)
{
}
function scorm_content_delivery_environment($seq, $userid)
{
}
function scorm_clear_suspended_activity($act, $seq, $userid)
{
}
function scorm_select_children_process($scoid, $userid)
{
}
function scorm_randomize_children_process($scoid, $userid)
{
}
function scorm_terminate_descendent_attempts($activity, $userid, $seq)
{
}
function scorm_sequencing_exception($seq)
{
}