<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Dataproc/AutotuningConfig.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Dataproc {
    class AutotuningConfig extends \Google\Collection
    {
        protected $collection_key = 'scenarios';
        /**
         * Optional. Scenarios for which tunings are applied.
         *
         * @var string[]
         */
        public $scenarios;
        /**
         * Optional. Scenarios for which tunings are applied.
         *
         * @param string[] $scenarios
         */
        public function setScenarios($scenarios)
        {
        }
        /**
         * @return string[]
         */
        public function getScenarios()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\Dataproc\AutotuningConfig registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_Dataproc_AutotuningConfig extends \Google\Service\Dataproc\AutotuningConfig
    {
    }
}