<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Dataproc/SearchSparkApplicationExecutorStageSummaryResponse.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Dataproc {
    class SearchSparkApplicationExecutorStageSummaryResponse extends \Google\Collection
    {
        protected $collection_key = 'sparkApplicationStageExecutors';
        /**
         * This token is included in the response if there are more results to fetch.
         * To fetch additional results, provide this value as the page_token in a
         * subsequent SearchSparkApplicationExecutorsListRequest.
         *
         * @var string
         */
        public $nextPageToken;
        protected $sparkApplicationStageExecutorsType = ExecutorStageSummary::class;
        protected $sparkApplicationStageExecutorsDataType = 'array';
        /**
         * This token is included in the response if there are more results to fetch.
         * To fetch additional results, provide this value as the page_token in a
         * subsequent SearchSparkApplicationExecutorsListRequest.
         *
         * @param string $nextPageToken
         */
        public function setNextPageToken($nextPageToken)
        {
        }
        /**
         * @return string
         */
        public function getNextPageToken()
        {
        }
        /**
         * Details about executors used by the application stage.
         *
         * @param ExecutorStageSummary[] $sparkApplicationStageExecutors
         */
        public function setSparkApplicationStageExecutors($sparkApplicationStageExecutors)
        {
        }
        /**
         * @return ExecutorStageSummary[]
         */
        public function getSparkApplicationStageExecutors()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\Dataproc\SearchSparkApplicationExecutorStageSummaryResponse registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_Dataproc_SearchSparkApplicationExecutorStageSummaryResponse extends \Google\Service\Dataproc\SearchSparkApplicationExecutorStageSummaryResponse
    {
    }
}