<?php

/**
 * Auto-generated stub file for Moodle's lib/phpspreadsheet/phpspreadsheet/src/PhpSpreadsheet/Chart/ChartColor.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
namespace PhpOffice\PhpSpreadsheet\Chart;

class ChartColor
{
    const EXCEL_COLOR_TYPE_STANDARD = 'prstClr';
    const EXCEL_COLOR_TYPE_SCHEME = 'schemeClr';
    const EXCEL_COLOR_TYPE_RGB = 'srgbClr';
    /** @deprecated 1.24 use EXCEL_COLOR_TYPE_RGB instead */
    const EXCEL_COLOR_TYPE_ARGB = 'srgbClr';
    const EXCEL_COLOR_TYPES = [self::EXCEL_COLOR_TYPE_ARGB, self::EXCEL_COLOR_TYPE_SCHEME, self::EXCEL_COLOR_TYPE_STANDARD];
    /** @var string */
    private $value = '';
    /** @var string */
    private $type = '';
    /** @var ?int */
    private $alpha;
    /** @var ?int */
    private $brightness;
    /**
     * @param string|string[] $value
     */
    public function __construct($value = '', ?int $alpha = null, ?string $type = null, ?int $brightness = null)
    {
    }
    public function getValue(): string
    {
    }
    public function setValue(string $value): self
    {
    }
    public function getType(): string
    {
    }
    public function setType(string $type): self
    {
    }
    public function getAlpha(): ?int
    {
    }
    public function setAlpha(?int $alpha): self
    {
    }
    public function getBrightness(): ?int
    {
    }
    public function setBrightness(?int $brightness): self
    {
    }
    /**
     * @param null|float|int|string $alpha
     * @param null|float|int|string $brightness
     */
    public function setColorProperties(?string $color, $alpha = null, ?string $type = null, $brightness = null): self
    {
    }
    public function setColorPropertiesArray(array $color): self
    {
    }
    public function isUsable(): bool
    {
    }
    /**
     * Get Color Property.
     *
     * @param string $propertyName
     *
     * @return null|int|string
     */
    public function getColorProperty($propertyName)
    {
    }
    public static function alphaToXml(int $alpha): string
    {
    }
    /**
     * @param float|int|string $alpha
     */
    public static function alphaFromXml($alpha): int
    {
    }
}