<?php

/**
 * Auto-generated stub file for Moodle's lib/google/contrib/Google_PagespeedonlineService.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
/**
 * The "pagespeedapi" collection of methods.
 * Typical usage is:
 *  <code>
 *   $pagespeedonlineService = new Google_PagespeedonlineService(...);
 *   $pagespeedapi = $pagespeedonlineService->pagespeedapi;
 *  </code>
 */
class Google_PagespeedapiServiceResource extends Google_ServiceResource
{
    /**
     * Runs Page Speed analysis on the page at the specified URL, and returns a Page Speed score, a list
     * of suggestions to make that page faster, and other information. (pagespeedapi.runpagespeed)
     *
     * @param string $url The URL to fetch and analyze
     * @param array $optParams Optional parameters.
     *
     * @opt_param string locale The locale used to localize formatted results
     * @opt_param string rule A Page Speed rule to run; if none are given, all rules are run
     * @opt_param string strategy The analysis strategy to use
     * @return Google_Result
     */
    public function runpagespeed($url, $optParams = array())
    {
    }
}
/**
 * Service definition for Google_Pagespeedonline (v1).
 *
 * <p>
 * Lets you analyze the performance of a web page and get tailored suggestions to make that page faster.
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="https://code.google.com/apis/pagespeedonline/v1/getting_started.html" target="_blank">API Documentation</a>
 * </p>
 *
 * @author Google, Inc.
 */
class Google_PagespeedonlineService extends Google_Service
{
    public $pagespeedapi;
    /**
     * Constructs the internal representation of the Pagespeedonline service.
     *
     * @param Google_Client $client
     */
    public function __construct(Google_Client $client)
    {
    }
}
class Google_Result extends Google_Model
{
    public $kind;
    protected $__formattedResultsType = 'Google_ResultFormattedResults';
    protected $__formattedResultsDataType = '';
    public $formattedResults;
    public $title;
    protected $__versionType = 'Google_ResultVersion';
    protected $__versionDataType = '';
    public $version;
    public $score;
    public $responseCode;
    public $invalidRules;
    protected $__pageStatsType = 'Google_ResultPageStats';
    protected $__pageStatsDataType = '';
    public $pageStats;
    public $id;
    public function setKind($kind)
    {
    }
    public function getKind()
    {
    }
    public function setFormattedResults(Google_ResultFormattedResults $formattedResults)
    {
    }
    public function getFormattedResults()
    {
    }
    public function setTitle($title)
    {
    }
    public function getTitle()
    {
    }
    public function setVersion(Google_ResultVersion $version)
    {
    }
    public function getVersion()
    {
    }
    public function setScore($score)
    {
    }
    public function getScore()
    {
    }
    public function setResponseCode($responseCode)
    {
    }
    public function getResponseCode()
    {
    }
    public function setInvalidRules(
        /* array(Google_string) */
        $invalidRules
    )
    {
    }
    public function getInvalidRules()
    {
    }
    public function setPageStats(Google_ResultPageStats $pageStats)
    {
    }
    public function getPageStats()
    {
    }
    public function setId($id)
    {
    }
    public function getId()
    {
    }
}
class Google_ResultFormattedResults extends Google_Model
{
    public $locale;
    protected $__ruleResultsType = 'Google_ResultFormattedResultsRuleResults';
    protected $__ruleResultsDataType = 'map';
    public $ruleResults;
    public function setLocale($locale)
    {
    }
    public function getLocale()
    {
    }
    public function setRuleResults(Google_ResultFormattedResultsRuleResults $ruleResults)
    {
    }
    public function getRuleResults()
    {
    }
}
class Google_ResultFormattedResultsRuleResults extends Google_Model
{
    public $localizedRuleName;
    protected $__urlBlocksType = 'Google_ResultFormattedResultsRuleResultsUrlBlocks';
    protected $__urlBlocksDataType = 'array';
    public $urlBlocks;
    public $ruleScore;
    public $ruleImpact;
    public function setLocalizedRuleName($localizedRuleName)
    {
    }
    public function getLocalizedRuleName()
    {
    }
    public function setUrlBlocks(
        /* array(Google_ResultFormattedResultsRuleResultsUrlBlocks) */
        $urlBlocks
    )
    {
    }
    public function getUrlBlocks()
    {
    }
    public function setRuleScore($ruleScore)
    {
    }
    public function getRuleScore()
    {
    }
    public function setRuleImpact($ruleImpact)
    {
    }
    public function getRuleImpact()
    {
    }
}
class Google_ResultFormattedResultsRuleResultsUrlBlocks extends Google_Model
{
    protected $__headerType = 'Google_ResultFormattedResultsRuleResultsUrlBlocksHeader';
    protected $__headerDataType = '';
    public $header;
    protected $__urlsType = 'Google_ResultFormattedResultsRuleResultsUrlBlocksUrls';
    protected $__urlsDataType = 'array';
    public $urls;
    public function setHeader(Google_ResultFormattedResultsRuleResultsUrlBlocksHeader $header)
    {
    }
    public function getHeader()
    {
    }
    public function setUrls(
        /* array(Google_ResultFormattedResultsRuleResultsUrlBlocksUrls) */
        $urls
    )
    {
    }
    public function getUrls()
    {
    }
}
class Google_ResultFormattedResultsRuleResultsUrlBlocksHeader extends Google_Model
{
    protected $__argsType = 'Google_ResultFormattedResultsRuleResultsUrlBlocksHeaderArgs';
    protected $__argsDataType = 'array';
    public $args;
    public $format;
    public function setArgs(
        /* array(Google_ResultFormattedResultsRuleResultsUrlBlocksHeaderArgs) */
        $args
    )
    {
    }
    public function getArgs()
    {
    }
    public function setFormat($format)
    {
    }
    public function getFormat()
    {
    }
}
class Google_ResultFormattedResultsRuleResultsUrlBlocksHeaderArgs extends Google_Model
{
    public $type;
    public $value;
    public function setType($type)
    {
    }
    public function getType()
    {
    }
    public function setValue($value)
    {
    }
    public function getValue()
    {
    }
}
class Google_ResultFormattedResultsRuleResultsUrlBlocksUrls extends Google_Model
{
    protected $__detailsType = 'Google_ResultFormattedResultsRuleResultsUrlBlocksUrlsDetails';
    protected $__detailsDataType = 'array';
    public $details;
    protected $__resultType = 'Google_ResultFormattedResultsRuleResultsUrlBlocksUrlsResult';
    protected $__resultDataType = '';
    public $result;
    public function setDetails(
        /* array(Google_ResultFormattedResultsRuleResultsUrlBlocksUrlsDetails) */
        $details
    )
    {
    }
    public function getDetails()
    {
    }
    public function setResult(Google_ResultFormattedResultsRuleResultsUrlBlocksUrlsResult $result)
    {
    }
    public function getResult()
    {
    }
}
class Google_ResultFormattedResultsRuleResultsUrlBlocksUrlsDetails extends Google_Model
{
    protected $__argsType = 'Google_ResultFormattedResultsRuleResultsUrlBlocksUrlsDetailsArgs';
    protected $__argsDataType = 'array';
    public $args;
    public $format;
    public function setArgs(
        /* array(Google_ResultFormattedResultsRuleResultsUrlBlocksUrlsDetailsArgs) */
        $args
    )
    {
    }
    public function getArgs()
    {
    }
    public function setFormat($format)
    {
    }
    public function getFormat()
    {
    }
}
class Google_ResultFormattedResultsRuleResultsUrlBlocksUrlsDetailsArgs extends Google_Model
{
    public $type;
    public $value;
    public function setType($type)
    {
    }
    public function getType()
    {
    }
    public function setValue($value)
    {
    }
    public function getValue()
    {
    }
}
class Google_ResultFormattedResultsRuleResultsUrlBlocksUrlsResult extends Google_Model
{
    protected $__argsType = 'Google_ResultFormattedResultsRuleResultsUrlBlocksUrlsResultArgs';
    protected $__argsDataType = 'array';
    public $args;
    public $format;
    public function setArgs(
        /* array(Google_ResultFormattedResultsRuleResultsUrlBlocksUrlsResultArgs) */
        $args
    )
    {
    }
    public function getArgs()
    {
    }
    public function setFormat($format)
    {
    }
    public function getFormat()
    {
    }
}
class Google_ResultFormattedResultsRuleResultsUrlBlocksUrlsResultArgs extends Google_Model
{
    public $type;
    public $value;
    public function setType($type)
    {
    }
    public function getType()
    {
    }
    public function setValue($value)
    {
    }
    public function getValue()
    {
    }
}
class Google_ResultPageStats extends Google_Model
{
    public $otherResponseBytes;
    public $flashResponseBytes;
    public $totalRequestBytes;
    public $numberCssResources;
    public $numberResources;
    public $cssResponseBytes;
    public $javascriptResponseBytes;
    public $imageResponseBytes;
    public $numberHosts;
    public $numberStaticResources;
    public $htmlResponseBytes;
    public $numberJsResources;
    public $textResponseBytes;
    public function setOtherResponseBytes($otherResponseBytes)
    {
    }
    public function getOtherResponseBytes()
    {
    }
    public function setFlashResponseBytes($flashResponseBytes)
    {
    }
    public function getFlashResponseBytes()
    {
    }
    public function setTotalRequestBytes($totalRequestBytes)
    {
    }
    public function getTotalRequestBytes()
    {
    }
    public function setNumberCssResources($numberCssResources)
    {
    }
    public function getNumberCssResources()
    {
    }
    public function setNumberResources($numberResources)
    {
    }
    public function getNumberResources()
    {
    }
    public function setCssResponseBytes($cssResponseBytes)
    {
    }
    public function getCssResponseBytes()
    {
    }
    public function setJavascriptResponseBytes($javascriptResponseBytes)
    {
    }
    public function getJavascriptResponseBytes()
    {
    }
    public function setImageResponseBytes($imageResponseBytes)
    {
    }
    public function getImageResponseBytes()
    {
    }
    public function setNumberHosts($numberHosts)
    {
    }
    public function getNumberHosts()
    {
    }
    public function setNumberStaticResources($numberStaticResources)
    {
    }
    public function getNumberStaticResources()
    {
    }
    public function setHtmlResponseBytes($htmlResponseBytes)
    {
    }
    public function getHtmlResponseBytes()
    {
    }
    public function setNumberJsResources($numberJsResources)
    {
    }
    public function getNumberJsResources()
    {
    }
    public function setTextResponseBytes($textResponseBytes)
    {
    }
    public function getTextResponseBytes()
    {
    }
}
class Google_ResultVersion extends Google_Model
{
    public $major;
    public $minor;
    public function setMajor($major)
    {
    }
    public function getMajor()
    {
    }
    public function setMinor($minor)
    {
    }
    public function getMinor()
    {
    }
}