<?php

/**
 * Auto-generated stub file for Moodle's public/auth/classes/output/oauth2/confirm_scopes_page.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
namespace core_auth\output\oauth2;

use League\OAuth2\Server\Entities\ScopeEntityInterface;
use core\router\scope\abstract_scope;
/**
 * Renderable for the Confirm Scopes page.
 *
 * @package    core_auth
 * @copyright  Andrew Lyons <andrew@nicols.co.uk>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class confirm_scopes_page extends oauth2_page
{
    /**
     * Create an instance of the form page.
     *
     * @param \League\OAuth2\Server\Entities\ClientEntityInterface $client The client entity
     * @param array $grantedscopes The list of scopes the user has already granted
     * @param array $requestedscopes The list of scopes the client is requesting
     * @param \core\url $actionurl The URL the scope confirmation form should submit to
     * @param \stdClass $user The user entity
     */
    public function __construct(
        \League\OAuth2\Server\Entities\ClientEntityInterface $client,
        /** @var array The list of scopes the user has already granted */
        protected array $grantedscopes,
        /** @var array The list of scopes the client is requesting */
        protected array $requestedscopes,
        /** @var \core\url The URL the scope confirmation form should submit to */
        private \core\url $actionurl,
        /** @var \stdClass The user entity */
        protected \stdClass $user
    )
    {
    }
    #[\Override]
    public function export_for_template(\core\output\renderer_base $renderer): \stdClass
    {
    }
    #[\Override]
    public function get_template_name(\core\output\renderer_base $renderer): string
    {
    }
}