<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Sheets/DataSourceSpec.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Sheets;

class DataSourceSpec extends \Google\Collection
{
    protected $collection_key = 'parameters';
    protected $bigQueryType = BigQueryDataSourceSpec::class;
    protected $bigQueryDataType = '';
    protected $lookerType = LookerDataSourceSpec::class;
    protected $lookerDataType = '';
    protected $parametersType = DataSourceParameter::class;
    protected $parametersDataType = 'array';
    /**
     * A BigQueryDataSourceSpec.
     *
     * @param BigQueryDataSourceSpec $bigQuery
     */
    public function setBigQuery(BigQueryDataSourceSpec $bigQuery)
    {
    }
    /**
     * @return BigQueryDataSourceSpec
     */
    public function getBigQuery()
    {
    }
    /**
     * A LookerDatasourceSpec.
     *
     * @param LookerDataSourceSpec $looker
     */
    public function setLooker(LookerDataSourceSpec $looker)
    {
    }
    /**
     * @return LookerDataSourceSpec
     */
    public function getLooker()
    {
    }
    /**
     * The parameters of the data source, used when querying the data source.
     *
     * @param DataSourceParameter[] $parameters
     */
    public function setParameters($parameters)
    {
    }
    /**
     * @return DataSourceParameter[]
     */
    public function getParameters()
    {
    }
}