<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Sheets/EmbeddedChart.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Sheets;

class EmbeddedChart extends \Google\Model
{
    protected $borderType = EmbeddedObjectBorder::class;
    protected $borderDataType = '';
    /**
     * The ID of the chart.
     *
     * @var int
     */
    public $chartId;
    protected $positionType = EmbeddedObjectPosition::class;
    protected $positionDataType = '';
    protected $specType = ChartSpec::class;
    protected $specDataType = '';
    /**
     * The border of the chart.
     *
     * @param EmbeddedObjectBorder $border
     */
    public function setBorder(EmbeddedObjectBorder $border)
    {
    }
    /**
     * @return EmbeddedObjectBorder
     */
    public function getBorder()
    {
    }
    /**
     * The ID of the chart.
     *
     * @param int $chartId
     */
    public function setChartId($chartId)
    {
    }
    /**
     * @return int
     */
    public function getChartId()
    {
    }
    /**
     * The position of the chart.
     *
     * @param EmbeddedObjectPosition $position
     */
    public function setPosition(EmbeddedObjectPosition $position)
    {
    }
    /**
     * @return EmbeddedObjectPosition
     */
    public function getPosition()
    {
    }
    /**
     * The specification of the chart.
     *
     * @param ChartSpec $spec
     */
    public function setSpec(ChartSpec $spec)
    {
    }
    /**
     * @return ChartSpec
     */
    public function getSpec()
    {
    }
}