<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/HangoutsChat/Card.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\HangoutsChat {
    class Card extends \Google\Collection
    {
        protected $collection_key = 'sections';
        protected $cardActionsType = CardAction::class;
        protected $cardActionsDataType = 'array';
        protected $headerType = CardHeader::class;
        protected $headerDataType = '';
        /**
         * Name of the card.
         *
         * @var string
         */
        public $name;
        protected $sectionsType = Section::class;
        protected $sectionsDataType = 'array';
        /**
         * The actions of this card.
         *
         * @param CardAction[] $cardActions
         */
        public function setCardActions($cardActions)
        {
        }
        /**
         * @return CardAction[]
         */
        public function getCardActions()
        {
        }
        /**
         * The header of the card. A header usually contains a title and an image.
         *
         * @param CardHeader $header
         */
        public function setHeader(CardHeader $header)
        {
        }
        /**
         * @return CardHeader
         */
        public function getHeader()
        {
        }
        /**
         * Name of the card.
         *
         * @param string $name
         */
        public function setName($name)
        {
        }
        /**
         * @return string
         */
        public function getName()
        {
        }
        /**
         * Sections are separated by a line divider.
         *
         * @param Section[] $sections
         */
        public function setSections($sections)
        {
        }
        /**
         * @return Section[]
         */
        public function getSections()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\HangoutsChat\Card registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_HangoutsChat_Card extends \Google\Service\HangoutsChat\Card
    {
    }
}