<?php

/**
 * Auto-generated stub file for Moodle's public/lib/classes/task/cleanup_questions_without_categories_task.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
namespace core\task;

use core\local\cli\shutdown;
/**
 * Task to find questions with no category and delete them
 *
 * Due to MDL-86154, there may be questions left in the database after a restore, whose category has been deleted.
 * This will find any questions like that and delete them. These questions will always be unused.
 *
 * Now that we have prevented this occurring, this task is used by the upgrade process to clean up these questions.
 *
 * @package   core
 * @copyright 2026 Martin Gauk <martin.gauk@tu-berlin.de>
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class cleanup_questions_without_categories_task extends adhoc_task
{
    use stored_progress_task_trait;
    #[\Override]
    public function execute()
    {
    }
}