<?php

/**
 * Auto-generated stub file for Moodle's lib/modinfolib.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/**
 * Information about a course that is cached in the course table 'modinfo' field (and then in
 * memory) in order to reduce the need for other database queries.
 *
 * This includes information about the course-modules and the sections on the course. It can also
 * include dynamic data that has been updated for the current user.
 */
class course_modinfo extends stdClass
{
    // For convenience we store the course object here as it is needed in other parts of code
    private $course;
    // Array of section data from cache
    private $sectioninfo;
    // Existing data fields
    ///////////////////////
    // These are public for backward compatibility. Note: it is not possible to retain BC
    // using PHP magic get methods because behaviour is different with regard to empty().
    /**
     * Course ID
     * @var int
     * @deprecated For new code, use get_course_id instead.
     */
    public $courseid;
    /**
     * User ID
     * @var int
     * @deprecated For new code, use get_user_id instead.
     */
    public $userid;
    /**
     * Array from int (section num, e.g. 0) => array of int (course-module id); this list only
     * includes sections that actually contain at least one course-module
     * @var array
     * @deprecated For new code, use get_sections instead
     */
    public $sections;
    /**
     * Array from int (cm id) => cm_info object
     * @var array
     * @deprecated For new code, use get_cms or get_cm instead.
     */
    public $cms;
    /**
     * Array from string (modname) => int (instance id) => cm_info object
     * @var array
     * @deprecated For new code, use get_instances or get_instances_of instead.
     */
    public $instances;
    /**
     * Groups that the current user belongs to. This value is usually not available (set to null)
     * unless the course has activities set to groupmembersonly. When set, it is an array of
     * grouping id => array of group id => group id. Includes grouping id 0 for 'all groups'.
     * @var array
     * @deprecated Don't use this! For new code, use get_groups.
     */
    public $groups;
    // Get methods for data
    ///////////////////////
    /**
     * @return object Moodle course object that was used to construct this data
     */
    public function get_course()
    {
    }
    /**
     * @return int Course ID
     */
    public function get_course_id()
    {
    }
    /**
     * @return int User ID
     */
    public function get_user_id()
    {
    }
    /**
     * @return array Array from section number (e.g. 0) to array of course-module IDs in that
     *   section; this only includes sections that contain at least one course-module
     */
    public function get_sections()
    {
    }
    /**
     * @return array Array from course-module instance to cm_info object within this course, in
     *   order of appearance
     */
    public function get_cms()
    {
    }
    /**
     * Obtains a single course-module object (for a course-module that is on this course).
     * @param int $cmid Course-module ID
     * @return cm_info Information about that course-module
     * @throws moodle_exception If the course-module does not exist
     */
    public function get_cm($cmid)
    {
    }
    /**
     * Obtains all module instances on this course.
     * @return array Array from module name => array from instance id => cm_info
     */
    public function get_instances()
    {
    }
    /**
     * Returns array of localised human-readable module names used in this course
     *
     * @param bool $plural if true returns the plural form of modules names
     * @return array
     */
    public function get_used_module_names($plural = false)
    {
    }
    /**
     * Obtains all instances of a particular module on this course.
     * @param $modname Name of module (not full frankenstyle) e.g. 'label'
     * @return array Array from instance id => cm_info for modules on this course; empty if none
     */
    public function get_instances_of($modname)
    {
    }
    /**
     * Returns groups that the current user belongs to on the course. Note: If not already
     * available, this may make a database query.
     * @param int $groupingid Grouping ID or 0 (default) for all groups
     * @return array Array of int (group id) => int (same group id again); empty array if none
     */
    public function get_groups($groupingid = 0)
    {
    }
    /**
     * Gets all sections as array from section number => data about section.
     * @return array Array of section_info objects organised by section number
     */
    public function get_section_info_all()
    {
    }
    /**
     * Gets data about specific numbered section.
     * @param int $sectionnumber Number (not id) of section
     * @param int $strictness Use MUST_EXIST to throw exception if it doesn't
     * @return section_info Information for numbered section or null if not found
     */
    public function get_section_info($sectionnumber, $strictness = IGNORE_MISSING)
    {
    }
    /**
     * Constructs based on course.
     * Note: This constructor should not usually be called directly.
     * Use get_fast_modinfo($course) instead as this maintains a cache.
     * @param object $course Moodle course object, which may include modinfo
     * @param int $userid User ID
     */
    public function __construct($course, $userid)
    {
    }
    /**
     * Builds a list of information about sections on a course to be stored in
     * the course cache. (Does not include information that is already cached
     * in some other way.)
     *
     * Used internally by rebuild_course_cache function; do not use otherwise.
     * @param int $courseid Course ID
     * @return array Information about sections, indexed by section number (not id)
     */
    public static function build_section_cache($courseid)
    {
    }
}
/**
 * Data about a single module on a course. This contains most of the fields in the course_modules
 * table, plus additional data when required.
 *
 * This object has many public fields; code should treat all these fields as read-only and set
 * data only using the supplied set functions. Setting the fields directly is not supported
 * and may cause problems later.
 */
class cm_info extends stdClass
{
    /**
     * State: Only basic data from modinfo cache is available.
     */
    const STATE_BASIC = 0;
    /**
     * State: Dynamic data is available too.
     */
    const STATE_DYNAMIC = 1;
    /**
     * State: View data (for course page) is available.
     */
    const STATE_VIEW = 2;
    /**
     * Parent object
     * @var course_modinfo
     */
    private $modinfo;
    /**
     * Level of information stored inside this object (STATE_xx constant)
     * @var int
     */
    private $state;
    // Existing data fields
    ///////////////////////
    /**
     * Course-module ID - from course_modules table
     * @var int
     */
    public $id;
    /**
     * Module instance (ID within module table) - from course_modules table
     * @var int
     */
    public $instance;
    /**
     * Course ID - from course_modules table
     * @var int
     */
    public $course;
    /**
     * 'ID number' from course-modules table (arbitrary text set by user) - from
     * course_modules table
     * @var string
     */
    public $idnumber;
    /**
     * Time that this course-module was added (unix time) - from course_modules table
     * @var int
     */
    public $added;
    /**
     * This variable is not used and is included here only so it can be documented.
     * Once the database entry is removed from course_modules, it should be deleted
     * here too.
     * @var int
     * @deprecated Do not use this variable
     */
    public $score;
    /**
     * Visible setting (0 or 1; if this is 0, students cannot see/access the activity) - from
     * course_modules table
     * @var int
     */
    public $visible;
    /**
     * Old visible setting (if the entire section is hidden, the previous value for
     * visible is stored in this field) - from course_modules table
     * @var int
     */
    public $visibleold;
    /**
     * Group mode (one of the constants NONE, SEPARATEGROUPS, or VISIBLEGROUPS) - from
     * course_modules table
     * @var int
     */
    public $groupmode;
    /**
     * Grouping ID (0 = all groupings)
     * @var int
     */
    public $groupingid;
    /**
     * Group members only (if set to 1, only members of a suitable group see this link on the
     * course page; 0 = everyone sees it even if they don't belong to a suitable group)  - from
     * course_modules table
     * @var int
     */
    public $groupmembersonly;
    /**
     * Indent level on course page (0 = no indent) - from course_modules table
     * @var int
     */
    public $indent;
    /**
     * Activity completion setting for this activity, COMPLETION_TRACKING_xx constant - from
     * course_modules table
     * @var int
     */
    public $completion;
    /**
     * Set to the item number (usually 0) if completion depends on a particular
     * grade of this activity, or null if completion does not depend on a grade - from
     * course_modules table
     * @var mixed
     */
    public $completiongradeitemnumber;
    /**
     * 1 if 'on view' completion is enabled, 0 otherwise - from course_modules table
     * @var int
     */
    public $completionview;
    /**
     * Set to a unix time if completion of this activity is expected at a
     * particular time, 0 if no time set - from course_modules table
     * @var int
     */
    public $completionexpected;
    /**
     * Available date for this activity (0 if not set, or set to seconds since epoch; before this
     * date, activity does not display to students) - from course_modules table
     * @var int
     */
    public $availablefrom;
    /**
     * Available until date for this activity (0 if not set, or set to seconds since epoch; from
     * this date, activity does not display to students) - from course_modules table
     * @var int
     */
    public $availableuntil;
    /**
     * When activity is unavailable, this field controls whether it is shown to students (0 =
     * hide completely, 1 = show greyed out with information about when it will be available) -
     * from course_modules table
     * @var int
     */
    public $showavailability;
    /**
     * Controls whether the description of the activity displays on the course main page (in
     * addition to anywhere it might display within the activity itself). 0 = do not show
     * on main page, 1 = show on main page.
     * @var int
     */
    public $showdescription;
    /**
     * Extra HTML that is put in an unhelpful part of the HTML when displaying this module in
     * course page - from cached data in modinfo field
     * @deprecated This is crazy, don't use it. Replaced by ->extraclasses and ->onclick
     * @var string
     */
    public $extra;
    /**
     * Name of icon to use - from cached data in modinfo field
     * @var string
     */
    public $icon;
    /**
     * Component that contains icon - from cached data in modinfo field
     * @var string
     */
    public $iconcomponent;
    /**
     * Name of module e.g. 'forum' (this is the same name as the module's main database
     * table) - from cached data in modinfo field
     * @var string
     */
    public $modname;
    /**
     * ID of module - from course_modules table
     * @var int
     */
    public $module;
    /**
     * Name of module instance for display on page e.g. 'General discussion forum' - from cached
     * data in modinfo field
     * @var string
     */
    public $name;
    /**
     * Section number that this course-module is in (section 0 = above the calendar, section 1
     * = week/topic 1, etc) - from cached data in modinfo field
     * @var string
     */
    public $sectionnum;
    /**
     * Section id - from course_modules table
     * @var int
     */
    public $section;
    /**
     * Availability conditions for this course-module based on the completion of other
     * course-modules (array from other course-module id to required completion state for that
     * module) - from cached data in modinfo field
     * @var array
     */
    public $conditionscompletion;
    /**
     * Availability conditions for this course-module based on course grades (array from
     * grade item id to object with ->min, ->max fields) - from cached data in modinfo field
     * @var array
     */
    public $conditionsgrade;
    /**
     * Availability conditions for this course-module based on user fields
     * @var array
     */
    public $conditionsfield;
    /**
     * True if this course-module is available to students i.e. if all availability conditions
     * are met - obtained dynamically
     * @var bool
     */
    public $available;
    /**
     * If course-module is not available to students, this string gives information about
     * availability which can be displayed to students and/or staff (e.g. 'Available from 3
     * January 2010') for display on main page - obtained dynamically
     * @var string
     */
    public $availableinfo;
    /**
     * True if this course-module is available to the CURRENT user (for example, if current user
     * has viewhiddenactivities capability, they can access the course-module even if it is not
     * visible or not available, so this would be true in that case)
     * @var bool
     */
    public $uservisible;
    /**
     * Module context - hacky shortcut
     * @deprecated
     * @var stdClass
     */
    public $context;
    // New data available only via functions
    ////////////////////////////////////////
    /**
     * @var moodle_url
     */
    private $url;
    /**
     * @var string
     */
    private $content;
    /**
     * @var string
     */
    private $extraclasses;
    /**
     * @var moodle_url full external url pointing to icon image for activity
     */
    private $iconurl;
    /**
     * @var string
     */
    private $onclick;
    /**
     * @var mixed
     */
    private $customdata;
    /**
     * @var string
     */
    private $afterlink;
    /**
     * @var string
     */
    private $afterediticons;
    /**
     * Magic method getter
     *
     * @param string $name
     * @return mixed
     */
    public function __get($name)
    {
    }
    /**
     * @return bool True if this module has a 'view' page that should be linked to in navigation
     *   etc (note: modules may still have a view.php file, but return false if this is not
     *   intended to be linked to from 'normal' parts of the interface; this is what label does).
     */
    public function has_view()
    {
    }
    /**
     * @return moodle_url URL to link to for this module, or null if it doesn't have a view page
     */
    public function get_url()
    {
    }
    /**
     * Obtains content to display on main (view) page.
     * Note: Will collect view data, if not already obtained.
     * @return string Content to display on main page below link, or empty string if none
     */
    public function get_content()
    {
    }
    /**
     * Note: Will collect view data, if not already obtained.
     * @return string Extra CSS classes to add to html output for this activity on main page
     */
    public function get_extra_classes()
    {
    }
    /**
     * @return string Content of HTML on-click attribute. This string will be used literally
     * as a string so should be pre-escaped.
     */
    public function get_on_click()
    {
    }
    /**
     * @return mixed Optional custom data stored in modinfo cache for this activity, or null if none
     */
    public function get_custom_data()
    {
    }
    /**
     * Note: Will collect view data, if not already obtained.
     * @return string Extra HTML code to display after link
     */
    public function get_after_link()
    {
    }
    /**
     * Note: Will collect view data, if not already obtained.
     * @return string Extra HTML code to display after editing icons (e.g. more icons)
     */
    public function get_after_edit_icons()
    {
    }
    /**
     * @param moodle_core_renderer $output Output render to use, or null for default (global)
     * @return moodle_url Icon URL for a suitable icon to put beside this cm
     */
    public function get_icon_url($output = null)
    {
    }
    /**
     * Returns a localised human-readable name of the module type
     *
     * @param bool $plural return plural form
     * @return string
     */
    public function get_module_type_name($plural = false)
    {
    }
    /**
     * @return course_modinfo Modinfo object that this came from
     */
    public function get_modinfo()
    {
    }
    /**
     * @return object Moodle course object that was used to construct this data
     */
    public function get_course()
    {
    }
    // Set functions
    ////////////////
    /**
     * Sets content to display on course view page below link (if present).
     * @param string $content New content as HTML string (empty string if none)
     * @return void
     */
    public function set_content($content)
    {
    }
    /**
     * Sets extra classes to include in CSS.
     * @param string $extraclasses Extra classes (empty string if none)
     * @return void
     */
    public function set_extra_classes($extraclasses)
    {
    }
    /**
     * Sets the external full url that points to the icon being used
     * by the activity. Useful for external-tool modules (lti...)
     * If set, takes precedence over $icon and $iconcomponent
     *
     * @param moodle_url $iconurl full external url pointing to icon image for activity
     * @return void
     */
    public function set_icon_url(moodle_url $iconurl)
    {
    }
    /**
     * Sets value of on-click attribute for JavaScript.
     * Note: May not be called from _cm_info_view (only _cm_info_dynamic).
     * @param string $onclick New onclick attribute which should be HTML-escaped
     *   (empty string if none)
     * @return void
     */
    public function set_on_click($onclick)
    {
    }
    /**
     * Sets HTML that displays after link on course view page.
     * @param string $afterlink HTML string (empty string if none)
     * @return void
     */
    public function set_after_link($afterlink)
    {
    }
    /**
     * Sets HTML that displays after edit icons on course view page.
     * @param string $afterediticons HTML string (empty string if none)
     * @return void
     */
    public function set_after_edit_icons($afterediticons)
    {
    }
    /**
     * Changes the name (text of link) for this module instance.
     * Note: May not be called from _cm_info_view (only _cm_info_dynamic).
     * @param string $name Name of activity / link text
     * @return void
     */
    public function set_name($name)
    {
    }
    /**
     * Turns off the view link for this module instance.
     * Note: May not be called from _cm_info_view (only _cm_info_dynamic).
     * @return void
     */
    public function set_no_view_link()
    {
    }
    /**
     * Sets the 'uservisible' flag. This can be used (by setting false) to prevent access and
     * display of this module link for the current user.
     * Note: May not be called from _cm_info_view (only _cm_info_dynamic).
     * @param bool $uservisible
     * @return void
     */
    public function set_user_visible($uservisible)
    {
    }
    /**
     * Sets the 'available' flag and related details. This flag is normally used to make
     * course modules unavailable until a certain date or condition is met. (When a course
     * module is unavailable, it is still visible to users who have viewhiddenactivities
     * permission.)
     *
     * When this is function is called, user-visible status is recalculated automatically.
     *
     * Note: May not be called from _cm_info_view (only _cm_info_dynamic).
     * @param bool $available False if this item is not 'available'
     * @param int $showavailability 0 = do not show this item at all if it's not available,
     *   1 = show this item greyed out with the following message
     * @param string $availableinfo Information about why this is not available which displays
     *   to those who have viewhiddenactivities, and to everyone if showavailability is set;
     *   note that this function replaces the existing data (if any)
     * @return void
     */
    public function set_available($available, $showavailability = 0, $availableinfo = '')
    {
    }
    /**
     * Some set functions can only be called from _cm_info_dynamic and not _cm_info_view.
     * This is because they may affect parts of this object which are used on pages other
     * than the view page (e.g. in the navigation block, or when checking access on
     * module pages).
     * @return void
     */
    private function check_not_view_only()
    {
    }
    /**
     * Constructor should not be called directly; use get_fast_modinfo.
     * @param course_modinfo $modinfo Parent object
     * @param object $course Course row
     * @param object $mod Module object from the modinfo field of course table
     * @param object $info Entire object from modinfo field of course table
     */
    public function __construct(course_modinfo $modinfo, $course, $mod, $info)
    {
    }
    /**
     * If dynamic data for this course-module is not yet available, gets it.
     *
     * This function is automatically called when constructing course_modinfo, so users don't
     * need to call it.
     *
     * Dynamic data is data which does not come directly from the cache but is calculated at
     * runtime based on the current user. Primarily this concerns whether the user can access
     * the module or not.
     *
     * As part of this function, the module's _cm_info_dynamic function from its lib.php will
     * be called (if it exists).
     * @return void
     */
    public function obtain_dynamic_data()
    {
    }
    /**
     * Works out whether activity is available to the current user
     *
     * If the activity is unavailable, additional checks are required to determine if its hidden or greyed out
     *
     * @see is_user_access_restricted_by_group()
     * @see is_user_access_restricted_by_conditional_access()
     * @return void
     */
    private function update_user_visible()
    {
    }
    /**
     * Checks whether the module's group settings restrict the current user's access
     *
     * @return bool True if the user access is restricted
     */
    public function is_user_access_restricted_by_group()
    {
    }
    /**
     * Checks whether mod/...:view capability restricts the current user's access.
     *
     * @return bool True if the user access is restricted.
     */
    public function is_user_access_restricted_by_capability()
    {
    }
    /**
     * Checks whether the module's conditional access settings mean that the user cannot see the activity at all
     *
     * @return bool True if the user cannot see the module. False if the activity is either available or should be greyed out.
     */
    public function is_user_access_restricted_by_conditional_access()
    {
    }
    /**
     * Calls a module function (if exists), passing in one parameter: this object.
     * @param string $type Name of function e.g. if this is 'grooblezorb' and the modname is
     *   'forum' then it will try to call 'mod_forum_grooblezorb' or 'forum_grooblezorb'
     * @return void
     */
    private function call_mod_function($type)
    {
    }
    /**
     * If view data for this course-module is not yet available, obtains it.
     *
     * This function is automatically called if any of the functions (marked) which require
     * view data are called.
     *
     * View data is data which is needed only for displaying the course main page (& any similar
     * functionality on other pages) but is not needed in general. Obtaining view data may have
     * a performance cost.
     *
     * As part of this function, the module's _cm_info_view function from its lib.php will
     * be called (if it exists).
     * @return void
     */
    private function obtain_view_data()
    {
    }
}
/**
 * Returns reference to full info about modules in course (including visibility).
 * Cached and as fast as possible (0 or 1 db query).
 *
 * use get_fast_modinfo($courseid, 0, true) to reset the static cache for particular course
 * use get_fast_modinfo(0, 0, true) to reset the static cache for all courses
 *
 * @uses MAX_MODINFO_CACHE_SIZE
 * @param int|stdClass $courseorid object from DB table 'course' or just a course id
 * @param int $userid User id to populate 'uservisible' attributes of modules and sections.
 *     Set to 0 for current user (default)
 * @param bool $resetonly whether we want to get modinfo or just reset the cache
 * @return course_modinfo|null Module information for course, or null if resetting
 */
function get_fast_modinfo($courseorid, $userid = 0, $resetonly = false)
{
}
/**
 * Rebuilds the cached list of course activities stored in the database
 * @param int $courseid - id of course to rebuild, empty means all
 * @param boolean $clearonly - only clear the modinfo fields, gets rebuild automatically on the fly
 */
function rebuild_course_cache($courseid = 0, $clearonly = false)
{
}
/**
 * Class that is the return value for the _get_coursemodule_info module API function.
 *
 * Note: For backward compatibility, you can also return a stdclass object from that function.
 * The difference is that the stdclass object may contain an 'extra' field (deprecated because
 * it was crazy, except for label which uses it differently). The stdclass object may not contain
 * the new fields defined here (content, extraclasses, customdata).
 */
class cached_cm_info
{
    /**
     * Name (text of link) for this activity; Leave unset to accept default name
     * @var string
     */
    public $name;
    /**
     * Name of icon for this activity. Normally, this should be used together with $iconcomponent
     * to define the icon, as per pix_url function.
     * For backward compatibility, if this value is of the form 'mod/forum/icon' then an icon
     * within that module will be used.
     * @see cm_info::get_icon_url()
     * @see renderer_base::pix_url()
     * @var string
     */
    public $icon;
    /**
     * Component for icon for this activity, as per pix_url; leave blank to use default 'moodle'
     * component
     * @see renderer_base::pix_url()
     * @var string
     */
    public $iconcomponent;
    /**
     * HTML content to be displayed on the main page below the link (if any) for this course-module
     * @var string
     */
    public $content;
    /**
     * Custom data to be stored in modinfo for this activity; useful if there are cases when
     * internal information for this activity type needs to be accessible from elsewhere on the
     * course without making database queries. May be of any type but should be short.
     * @var mixed
     */
    public $customdata;
    /**
     * Extra CSS class or classes to be added when this activity is displayed on the main page;
     * space-separated string
     * @var string
     */
    public $extraclasses;
    /**
     * External URL image to be used by activity as icon, useful for some external-tool modules
     * like lti. If set, takes precedence over $icon and $iconcomponent
     * @var $moodle_url
     */
    public $iconurl;
    /**
     * Content of onclick JavaScript; escaped HTML to be inserted as attribute value
     * @var string
     */
    public $onclick;
}
/**
 * Data about a single section on a course. This contains the fields from the
 * course_sections table, plus additional data when required.
 */
class section_info implements IteratorAggregate
{
    /**
     * Section ID - from course_sections table
     * @var int
     */
    private $_id;
    /**
     * Course ID - from course_sections table
     * @var int
     */
    private $_course;
    /**
     * Section number - from course_sections table
     * @var int
     */
    private $_section;
    /**
     * Section name if specified - from course_sections table
     * @var string
     */
    private $_name;
    /**
     * Section visibility (1 = visible) - from course_sections table
     * @var int
     */
    private $_visible;
    /**
     * Section summary text if specified - from course_sections table
     * @var string
     */
    private $_summary;
    /**
     * Section summary text format (FORMAT_xx constant) - from course_sections table
     * @var int
     */
    private $_summaryformat;
    /**
     * When section is unavailable, this field controls whether it is shown to students (0 =
     * hide completely, 1 = show greyed out with information about when it will be available) -
     * from course_sections table
     * @var int
     */
    private $_showavailability;
    /**
     * Available date for this section (0 if not set, or set to seconds since epoch; before this
     * date, section does not display to students) - from course_sections table
     * @var int
     */
    private $_availablefrom;
    /**
     * Available until date for this section  (0 if not set, or set to seconds since epoch; from
     * this date, section does not display to students) - from course_sections table
     * @var int
     */
    private $_availableuntil;
    /**
     * If section is restricted to users of a particular grouping, this is its id
     * (0 if not set) - from course_sections table
     * @var int
     */
    private $_groupingid;
    /**
     * Availability conditions for this section based on the completion of
     * course-modules (array from course-module id to required completion state
     * for that module) - from cached data in sectioncache field
     * @var array
     */
    private $_conditionscompletion;
    /**
     * Availability conditions for this section based on course grades (array from
     * grade item id to object with ->min, ->max fields) - from cached data in
     * sectioncache field
     * @var array
     */
    private $_conditionsgrade;
    /**
     * Availability conditions for this section based on user fields
     * @var array
     */
    private $_conditionsfield;
    /**
     * True if this section is available to students i.e. if all availability conditions
     * are met - obtained dynamically
     * @var bool
     */
    private $_available;
    /**
     * If section is not available to students, this string gives information about
     * availability which can be displayed to students and/or staff (e.g. 'Available from 3
     * January 2010') for display on main page - obtained dynamically
     * @var string
     */
    private $_availableinfo;
    /**
     * True if this section is available to the CURRENT user (for example, if current user
     * has viewhiddensections capability, they can access the section even if it is not
     * visible or not available, so this would be true in that case)
     * @var bool
     */
    private $_uservisible;
    /**
     * Default values for sectioncache fields; if a field has this value, it won't
     * be stored in the sectioncache cache, to save space. Checks are done by ===
     * which means values must all be strings.
     * @var array
     */
    private static $sectioncachedefaults = array(
        'name' => null,
        'summary' => '',
        'summaryformat' => '1',
        // FORMAT_HTML, but must be a string
        'visible' => '1',
        'showavailability' => '0',
        'availablefrom' => '0',
        'availableuntil' => '0',
        'groupingid' => '0',
    );
    /**
     * Stores format options that have been cached when building 'coursecache'
     * When the format option is requested we look first if it has been cached
     * @var array
     */
    private $cachedformatoptions = array();
    /**
     * Constructs object from database information plus extra required data.
     * @param object $data Array entry from cached sectioncache
     * @param int $number Section number (array key)
     * @param int $courseid Course ID
     * @param int $sequence Sequence of course-module ids contained within
     * @param course_modinfo $modinfo Owner (needed for checking availability)
     * @param int $userid User ID
     */
    public function __construct($data, $number, $courseid, $sequence, $modinfo, $userid)
    {
    }
    /**
     * Magic method to check if the property is set
     *
     * @param string $name name of the property
     * @return bool
     */
    public function __isset($name)
    {
    }
    /**
     * Magic method to check if the property is empty
     *
     * @param string $name name of the property
     * @return bool
     */
    public function __empty($name)
    {
    }
    /**
     * Magic method to retrieve the property, this is either basic section property
     * or availability information or additional properties added by course format
     *
     * @param string $name name of the property
     * @return bool
     */
    public function __get($name)
    {
    }
    /**
     * Implementation of IteratorAggregate::getIterator(), allows to cycle through properties
     * and use {@link convert_to_array()}
     *
     * @return ArrayIterator
     */
    public function getIterator()
    {
    }
    /**
     * Works out whether activity is visible *for current user* - if this is false, they
     * aren't allowed to access it.
     * @param int $userid User ID
     * @return void
     */
    private function update_user_visible($userid)
    {
    }
    /**
     * Prepares section data for inclusion in sectioncache cache, removing items
     * that are set to defaults, and adding availability data if required.
     *
     * Called by build_section_cache in course_modinfo only; do not use otherwise.
     * @param object $section Raw section data object
     */
    public static function convert_for_section_cache($section)
    {
    }
}