<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/CloudSearch/Name.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\CloudSearch {
    class Name extends \Google\Model
    {
        /**
         * The read-only display name formatted according to the locale specified by
         * the viewer's account or the `Accept-Language` HTTP header.
         *
         * @var string
         */
        public $displayName;
        /**
         * The read-only display name formatted according to the locale specified by
         * the viewer's account or the `Accept-Language` HTTP header.
         *
         * @param string $displayName
         */
        public function setDisplayName($displayName)
        {
        }
        /**
         * @return string
         */
        public function getDisplayName()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\CloudSearch\Name registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_CloudSearch_Name extends \Google\Service\CloudSearch\Name
    {
    }
}