<?php

/**
 * Auto-generated stub file for Moodle's public/lib/aws-sdk/src/S3/S3Transfer/Progress/ProgressBarFactoryInterface.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
namespace Aws\S3\S3Transfer\Progress;

interface ProgressBarFactoryInterface
{
    public function __invoke(): ProgressBarInterface;
}