<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/FirebaseAppDistribution.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service {
    use Google\Client;
    /**
    * Service definition for FirebaseAppDistribution (v1).
    *
    * <p>
    </p>
    *
    * <p>
    * For more information about this service, see the API
    * <a href="https://firebase.google.com/products/app-distribution" target="_blank">Documentation</a>
    * </p>
    *
    * @author Google, Inc.
    */
    class FirebaseAppDistribution extends \Google\Service
    {
        /** See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account.. */
        const CLOUD_PLATFORM = "https://www.googleapis.com/auth/cloud-platform";
        public $media;
        public $projects_apps;
        public $projects_apps_releases;
        public $projects_apps_releases_feedbackReports;
        public $projects_apps_releases_operations;
        public $projects_groups;
        public $projects_testers;
        public $rootUrlTemplate;
        /**
         * Constructs the internal representation of the FirebaseAppDistribution
         * service.
         *
         * @param Client|array $clientOrConfig The client used to deliver requests, or a
         *                                     config array to pass to a new Client instance.
         * @param string $rootUrl The root URL used for requests to the service.
         */
        public function __construct($clientOrConfig = [], $rootUrl = null)
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\FirebaseAppDistribution registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_FirebaseAppDistribution extends \Google\Service\FirebaseAppDistribution
    {
    }
}