<?php

/**
 * Auto-generated stub file for Moodle's lib/zend/Zend/Gdata/Extension/Reminder.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/**
 * Implements the gd:reminder element used to set/retrieve notifications
 *
 * @category   Zend
 * @package    Zend_Gdata
 * @subpackage Gdata
 * @copyright  Copyright (c) 2005-2015 Zend Technologies USA Inc. (http://www.zend.com)
 * @license    http://framework.zend.com/license/new-bsd     New BSD License
 */
class Zend_Gdata_Extension_Reminder extends Zend_Gdata_Extension
{
    protected $_rootElement = 'reminder';
    protected $_absoluteTime = null;
    protected $_method = null;
    protected $_days = null;
    protected $_hours = null;
    protected $_minutes = null;
    public function __construct($absoluteTime = null, $method = null, $days = null, $hours = null, $minutes = null)
    {
    }
    public function getDOM($doc = null, $majorVersion = 1, $minorVersion = null)
    {
    }
    protected function takeAttributeFromDOM($attribute)
    {
    }
    public function __toString()
    {
    }
    public function getAbsoluteTime()
    {
    }
    public function setAbsoluteTime($value)
    {
    }
    public function getDays()
    {
    }
    public function setDays($value)
    {
    }
    public function getHours()
    {
    }
    public function setHours($value)
    {
    }
    public function getMinutes()
    {
    }
    public function setMinutes($value)
    {
    }
    public function getMethod()
    {
    }
    public function setMethod($value)
    {
    }
}