<?php

/**
 * Auto-generated stub file for Moodle's lib/zend/Zend/Json/Server/Exception.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/**
 * Zend_Json_Server exceptions
 *
 * @uses       Zend_Json_Exception
 * @package    Zend_Json
 * @subpackage Server
 * @copyright  Copyright (c) 2005-2015 Zend Technologies USA Inc. (http://www.zend.com)
 * @license    http://framework.zend.com/license/new-bsd     New BSD License
 */
class Zend_Json_Server_Exception extends Zend_Json_Exception
{
}