<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Pubsub/ListSchemasResponse.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Pubsub {
    class ListSchemasResponse extends \Google\Collection
    {
        protected $collection_key = 'schemas';
        /**
         * If not empty, indicates that there may be more schemas that match the
         * request; this value should be passed in a new `ListSchemasRequest`.
         *
         * @var string
         */
        public $nextPageToken;
        protected $schemasType = Schema::class;
        protected $schemasDataType = 'array';
        /**
         * If not empty, indicates that there may be more schemas that match the
         * request; this value should be passed in a new `ListSchemasRequest`.
         *
         * @param string $nextPageToken
         */
        public function setNextPageToken($nextPageToken)
        {
        }
        /**
         * @return string
         */
        public function getNextPageToken()
        {
        }
        /**
         * The resulting schemas.
         *
         * @param Schema[] $schemas
         */
        public function setSchemas($schemas)
        {
        }
        /**
         * @return Schema[]
         */
        public function getSchemas()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\Pubsub\ListSchemasResponse registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_Pubsub_ListSchemasResponse extends \Google\Service\Pubsub\ListSchemasResponse
    {
    }
}