<?php

/**
 * Auto-generated stub file for Moodle's lib/aws-sdk/src/PersonalizeRuntime/PersonalizeRuntimeClient.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
namespace Aws\PersonalizeRuntime;

/**
 * This client is used to interact with the **Amazon Personalize Runtime** service.
 * @method \Aws\Result getPersonalizedRanking(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getPersonalizedRankingAsync(array $args = [])
 * @method \Aws\Result getRecommendations(array $args = [])
 * @method \GuzzleHttp\Promise\Promise getRecommendationsAsync(array $args = [])
 */
class PersonalizeRuntimeClient extends AwsClient
{
}