<?php

/**
 * Auto-generated stub file for Moodle's mod/scorm/simpletest/test_formatduration.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
// Include the code to test
class scorm_formatduration_test extends UnitTestCase
{
    function test_scorm2004_format()
    {
    }
    function test_scorm12_format()
    {
    }
    function test_non_datetime()
    {
    }
}