<?php

/**
 * Auto-generated stub file for Moodle's mod/assignment/mod_form.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
class mod_assignment_mod_form extends moodleform_mod
{
    function definition()
    {
    }
}