<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/DisplayVideo/InventorySourceAccessorsAdvertiserAccessors.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\DisplayVideo {
    class InventorySourceAccessorsAdvertiserAccessors extends \Google\Collection
    {
        protected $collection_key = 'advertiserIds';
        /**
         * The IDs of the advertisers.
         *
         * @var string[]
         */
        public $advertiserIds;
        /**
         * The IDs of the advertisers.
         *
         * @param string[] $advertiserIds
         */
        public function setAdvertiserIds($advertiserIds)
        {
        }
        /**
         * @return string[]
         */
        public function getAdvertiserIds()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\DisplayVideo\InventorySourceAccessorsAdvertiserAccessors registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_DisplayVideo_InventorySourceAccessorsAdvertiserAccessors extends \Google\Service\DisplayVideo\InventorySourceAccessorsAdvertiserAccessors
    {
    }
}