<?php

/**
 * Auto-generated stub file for Moodle's public/course/classes/analytics/indicator/potential_cognitive_depth.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.
/**
 * Potential cognitive depth indicator.
 *
 * @package   core_course
 * @copyright 2017 David Monllao {@link http://www.davidmonllao.com}
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
namespace core_course\analytics\indicator;

use core_analytics\local\indicator\community_of_inquiry_activity;
/**
 * Potential cognitive depth indicator.
 *
 * It extends linear instead of discrete as there is a linear relation between
 * the different cognitive levels activities can reach.
 *
 * @package   core_course
 * @copyright 2017 David Monllao {@link http://www.davidmonllao.com}
 * @license   http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class potential_cognitive_depth extends \core_analytics\local\indicator\linear
{
    /**
     * get_name
     *
     * @return \lang_string
     */
    public static function get_name(): \lang_string
    {
    }
    /**
     * Specify the required data to process this indicator.
     *
     * @return string[]
     */
    public static function required_sample_data()
    {
    }
    /**
     * calculate_sample
     *
     * @throws \coding_exception
     * @param int $sampleid
     * @param string $sampleorigin
     * @param int|false $notusedstarttime
     * @param int|false $notusedendtime
     * @return float
     */
    public function calculate_sample($sampleid, $sampleorigin, $notusedstarttime = false, $notusedendtime = false)
    {
    }
    /**
     * Returns the cognitive depth class of this indicator.
     *
     * @param string $modname
     * @return \core_analytics\local\indicator\base|false
     */
    protected function get_cognitive_indicator($modname)
    {
    }
}