<?php

/**
 * Auto-generated stub file for Moodle's course/classes/reportbuilder/local/formatters/enrolment.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
namespace core_course\reportbuilder\local\formatters;

/**
 * Formatters for the course enrolment entity
 *
 * @package     core_course
 * @copyright   2022 David Matamoros <davidmc@moodle.com>
 * @license     http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class enrolment
{
    /**
     * @deprecated since Moodle 4.3 - please do not use this function any more (to remove in MDL-78118)
     */
    #[\core\attribute\deprecated(null, reason: 'It is no longer used', since: '4.3', mdl: 'MDL-76900', final: true)]
    public static function enrolment_name(): void
    {
    }
    /**
     * Returns list of enrolment statuses
     *
     * @return lang_string[]
     */
    public static function enrolment_values(): array
    {
    }
    /**
     * Return enrolment status for user
     *
     * @param string|null $value
     * @return string|null
     */
    public static function enrolment_status(?string $value): ?string
    {
    }
}