<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/Aiplatform/GoogleCloudAiplatformV1ProbeTcpSocketAction.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\Aiplatform {
    class GoogleCloudAiplatformV1ProbeTcpSocketAction extends \Google\Model
    {
        /**
         * Optional: Host name to connect to, defaults to the model serving
         * container's IP.
         *
         * @var string
         */
        public $host;
        /**
         * Number of the port to access on the container. Number must be in the range
         * 1 to 65535.
         *
         * @var int
         */
        public $port;
        /**
         * Optional: Host name to connect to, defaults to the model serving
         * container's IP.
         *
         * @param string $host
         */
        public function setHost($host)
        {
        }
        /**
         * @return string
         */
        public function getHost()
        {
        }
        /**
         * Number of the port to access on the container. Number must be in the range
         * 1 to 65535.
         *
         * @param int $port
         */
        public function setPort($port)
        {
        }
        /**
         * @return int
         */
        public function getPort()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\Aiplatform\GoogleCloudAiplatformV1ProbeTcpSocketAction registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_Aiplatform_GoogleCloudAiplatformV1ProbeTcpSocketAction extends \Google\Service\Aiplatform\GoogleCloudAiplatformV1ProbeTcpSocketAction
    {
    }
}