<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google/src/Google/Service/Classroom.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2010 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
/**
 * Service definition for Classroom (v1).
 *
 * <p>
 * Google Classroom API</p>
 *
 * <p>
 * For more information about this service, see the API
 * <a href="https://developers.google.com/classroom/" target="_blank">Documentation</a>
 * </p>
 *
 * @author Google, Inc.
 */
#[AllowDynamicProperties]
class Google_Service_Classroom extends Google_Service
{
    /** Manage your Google Classroom classes. */
    const CLASSROOM_COURSES = "https://www.googleapis.com/auth/classroom.courses";
    /** View your Google Classroom classes. */
    const CLASSROOM_COURSES_READONLY = "https://www.googleapis.com/auth/classroom.courses.readonly";
    /** View the email addresses of people in your classes. */
    const CLASSROOM_PROFILE_EMAILS = "https://www.googleapis.com/auth/classroom.profile.emails";
    /** View the profile photos of people in your classes. */
    const CLASSROOM_PROFILE_PHOTOS = "https://www.googleapis.com/auth/classroom.profile.photos";
    /** Manage your Google Classroom class rosters. */
    const CLASSROOM_ROSTERS = "https://www.googleapis.com/auth/classroom.rosters";
    /** View your Google Classroom class rosters. */
    const CLASSROOM_ROSTERS_READONLY = "https://www.googleapis.com/auth/classroom.rosters.readonly";
    public $courses;
    public $courses_aliases;
    public $courses_students;
    public $courses_teachers;
    public $invitations;
    public $userProfiles;
    /**
     * Constructs the internal representation of the Classroom service.
     *
     * @param Google_Client $client
     */
    public function __construct(Google_Client $client)
    {
    }
}
/**
 * The "courses" collection of methods.
 * Typical usage is:
 *  <code>
 *   $classroomService = new Google_Service_Classroom(...);
 *   $courses = $classroomService->courses;
 *  </code>
 */
#[AllowDynamicProperties]
class Google_Service_Classroom_Courses_Resource extends Google_Service_Resource
{
    /**
     * Creates a course. The user specified in `ownerId` is the owner of the created
     * course and added as a teacher. This method returns the following error codes:
     * * `PERMISSION_DENIED` if the requesting user is not permitted to create
     * courses or for access errors. * `NOT_FOUND` if the primary teacher is not a
     * valid user. * `FAILED_PRECONDITION` if the course owner's account is disabled
     * or for the following request errors: * UserGroupsMembershipLimitReached *
     * `ALREADY_EXISTS` if an alias was specified in the `id` and already exists.
     * (courses.create)
     *
     * @param Google_Course $postBody
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_Course
     */
    public function create(Google_Service_Classroom_Course $postBody, $optParams = array())
    {
    }
    /**
     * Deletes a course. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not permitted to delete the
     * requested course or for access errors. * `NOT_FOUND` if no course exists with
     * the requested ID. (courses.delete)
     *
     * @param string $id Identifier of the course to delete. This identifier can be
     * either the Classroom-assigned identifier or an alias.
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_Empty
     */
    public function delete($id, $optParams = array())
    {
    }
    /**
     * Returns a course. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not permitted to access the
     * requested course or for access errors. * `NOT_FOUND` if no course exists with
     * the requested ID. (courses.get)
     *
     * @param string $id Identifier of the course to return. This identifier can be
     * either the Classroom-assigned identifier or an alias.
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_Course
     */
    public function get($id, $optParams = array())
    {
    }
    /**
     * Returns a list of courses that the requesting user is permitted to view,
     * restricted to those that match the request. This method returns the following
     * error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if
     * the query argument is malformed. * `NOT_FOUND` if any users specified in the
     * query arguments do not exist. (courses.listCourses)
     *
     * @param array $optParams Optional parameters.
     *
     * @opt_param string teacherId Restricts returned courses to those having a
     * teacher with the specified identifier. The identifier can be one of the
     * following: * the numeric identifier for the user * the email address of the
     * user * the string literal `"me"`, indicating the requesting user
     * @opt_param string pageToken nextPageToken value returned from a previous list
     * call, indicating that the subsequent page of results should be returned. The
     * list request must be otherwise identical to the one that resulted in this
     * token.
     * @opt_param string studentId Restricts returned courses to those having a
     * student with the specified identifier. The identifier can be one of the
     * following: * the numeric identifier for the user * the email address of the
     * user * the string literal `"me"`, indicating the requesting user
     * @opt_param int pageSize Maximum number of items to return. Zero or
     * unspecified indicates that the server may assign a maximum. The server may
     * return fewer than the specified number of results.
     * @return Google_Service_Classroom_ListCoursesResponse
     */
    public function listCourses($optParams = array())
    {
    }
    /**
     * Updates one or more fields in a course. This method returns the following
     * error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
     * modify the requested course or for access errors. * `NOT_FOUND` if no course
     * exists with the requested ID. * `INVALID_ARGUMENT` if invalid fields are
     * specified in the update mask or if no update mask is supplied. *
     * `FAILED_PRECONDITION` for the following request errors: * CourseNotModifiable
     * (courses.patch)
     *
     * @param string $id Identifier of the course to update. This identifier can be
     * either the Classroom-assigned identifier or an alias.
     * @param Google_Course $postBody
     * @param array $optParams Optional parameters.
     *
     * @opt_param string updateMask Mask that identifies which fields on the course
     * to update. This field is required to do an update. The update will fail if
     * invalid fields are specified. The following fields are valid: * `name` *
     * `section` * `descriptionHeading` * `description` * `room` * `courseState`
     * When set in a query parameter, this field should be specified as
     * `updateMask=,,...`
     * @return Google_Service_Classroom_Course
     */
    public function patch($id, Google_Service_Classroom_Course $postBody, $optParams = array())
    {
    }
    /**
     * Updates a course. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not permitted to modify the
     * requested course or for access errors. * `NOT_FOUND` if no course exists with
     * the requested ID. * `FAILED_PRECONDITION` for the following request errors: *
     * CourseNotModifiable (courses.update)
     *
     * @param string $id Identifier of the course to update. This identifier can be
     * either the Classroom-assigned identifier or an alias.
     * @param Google_Course $postBody
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_Course
     */
    public function update($id, Google_Service_Classroom_Course $postBody, $optParams = array())
    {
    }
}
/**
 * The "aliases" collection of methods.
 * Typical usage is:
 *  <code>
 *   $classroomService = new Google_Service_Classroom(...);
 *   $aliases = $classroomService->aliases;
 *  </code>
 */
#[AllowDynamicProperties]
class Google_Service_Classroom_CoursesAliases_Resource extends Google_Service_Resource
{
    /**
     * Creates an alias for a course. This method returns the following error codes:
     * * `PERMISSION_DENIED` if the requesting user is not permitted to create the
     * alias or for access errors. * `NOT_FOUND` if the course does not exist. *
     * `ALREADY_EXISTS` if the alias already exists. (aliases.create)
     *
     * @param string $courseId Identifier of the course to alias. This identifier
     * can be either the Classroom-assigned identifier or an alias.
     * @param Google_CourseAlias $postBody
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_CourseAlias
     */
    public function create($courseId, Google_Service_Classroom_CourseAlias $postBody, $optParams = array())
    {
    }
    /**
     * Deletes an alias of a course. This method returns the following error codes:
     * * `PERMISSION_DENIED` if the requesting user is not permitted to remove the
     * alias or for access errors. * `NOT_FOUND` if the alias does not exist.
     * (aliases.delete)
     *
     * @param string $courseId Identifier of the course whose alias should be
     * deleted. This identifier can be either the Classroom-assigned identifier or
     * an alias.
     * @param string $alias Alias to delete. This may not be the Classroom-assigned
     * identifier.
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_Empty
     */
    public function delete($courseId, $alias, $optParams = array())
    {
    }
    /**
     * Returns a list of aliases for a course. This method returns the following
     * error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
     * access the course or for access errors. * `NOT_FOUND` if the course does not
     * exist. (aliases.listCoursesAliases)
     *
     * @param string $courseId The identifier of the course. This identifier can be
     * either the Classroom-assigned identifier or an alias.
     * @param array $optParams Optional parameters.
     *
     * @opt_param string pageToken nextPageToken value returned from a previous list
     * call, indicating that the subsequent page of results should be returned. The
     * list request must be otherwise identical to the one that resulted in this
     * token.
     * @opt_param int pageSize Maximum number of items to return. Zero or
     * unspecified indicates that the server may assign a maximum. The server may
     * return fewer than the specified number of results.
     * @return Google_Service_Classroom_ListCourseAliasesResponse
     */
    public function listCoursesAliases($courseId, $optParams = array())
    {
    }
}
/**
 * The "students" collection of methods.
 * Typical usage is:
 *  <code>
 *   $classroomService = new Google_Service_Classroom(...);
 *   $students = $classroomService->students;
 *  </code>
 */
#[AllowDynamicProperties]
class Google_Service_Classroom_CoursesStudents_Resource extends Google_Service_Resource
{
    /**
     * Adds a user as a student of a course. This method returns the following error
     * codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
     * create students in this course or for access errors. * `NOT_FOUND` if the
     * requested course ID does not exist. * `FAILED_PRECONDITION` if the requested
     * user's account is disabled, for the following request errors: *
     * CourseMemberLimitReached * CourseNotModifiable *
     * UserGroupsMembershipLimitReached * `ALREADY_EXISTS` if the user is already a
     * student or teacher in the course. (students.create)
     *
     * @param string $courseId Identifier of the course to create the student in.
     * This identifier can be either the Classroom-assigned identifier or an alias.
     * @param Google_Student $postBody
     * @param array $optParams Optional parameters.
     *
     * @opt_param string enrollmentCode Enrollment code of the course to create the
     * student in. This code is required if userId corresponds to the requesting
     * user; it may be omitted if the requesting user has administrative permissions
     * to create students for any user.
     * @return Google_Service_Classroom_Student
     */
    public function create($courseId, Google_Service_Classroom_Student $postBody, $optParams = array())
    {
    }
    /**
     * Deletes a student of a course. This method returns the following error codes:
     * * `PERMISSION_DENIED` if the requesting user is not permitted to delete
     * students of this course or for access errors. * `NOT_FOUND` if no student of
     * this course has the requested ID or if the course does not exist.
     * (students.delete)
     *
     * @param string $courseId Identifier of the course. This identifier can be
     * either the Classroom-assigned identifier or an alias.
     * @param string $userId Identifier of the student to delete. The identifier can
     * be one of the following: * the numeric identifier for the user * the email
     * address of the user * the string literal `"me"`, indicating the requesting
     * user
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_Empty
     */
    public function delete($courseId, $userId, $optParams = array())
    {
    }
    /**
     * Returns a student of a course. This method returns the following error codes:
     * * `PERMISSION_DENIED` if the requesting user is not permitted to view
     * students of this course or for access errors. * `NOT_FOUND` if no student of
     * this course has the requested ID or if the course does not exist.
     * (students.get)
     *
     * @param string $courseId Identifier of the course. This identifier can be
     * either the Classroom-assigned identifier or an alias.
     * @param string $userId Identifier of the student to return. The identifier can
     * be one of the following: * the numeric identifier for the user * the email
     * address of the user * the string literal `"me"`, indicating the requesting
     * user
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_Student
     */
    public function get($courseId, $userId, $optParams = array())
    {
    }
    /**
     * Returns a list of students of this course that the requester is permitted to
     * view. This method returns the following error codes: * `NOT_FOUND` if the
     * course does not exist. * `PERMISSION_DENIED` for access errors.
     * (students.listCoursesStudents)
     *
     * @param string $courseId Identifier of the course. This identifier can be
     * either the Classroom-assigned identifier or an alias.
     * @param array $optParams Optional parameters.
     *
     * @opt_param string pageToken nextPageToken value returned from a previous list
     * call, indicating that the subsequent page of results should be returned. The
     * list request must be otherwise identical to the one that resulted in this
     * token.
     * @opt_param int pageSize Maximum number of items to return. Zero means no
     * maximum. The server may return fewer than the specified number of results.
     * @return Google_Service_Classroom_ListStudentsResponse
     */
    public function listCoursesStudents($courseId, $optParams = array())
    {
    }
}
/**
 * The "teachers" collection of methods.
 * Typical usage is:
 *  <code>
 *   $classroomService = new Google_Service_Classroom(...);
 *   $teachers = $classroomService->teachers;
 *  </code>
 */
#[AllowDynamicProperties]
class Google_Service_Classroom_CoursesTeachers_Resource extends Google_Service_Resource
{
    /**
     * Creates a teacher of a course. This method returns the following error codes:
     * * `PERMISSION_DENIED` if the requesting user is not permitted to create
     * teachers in this course or for access errors. * `NOT_FOUND` if the requested
     * course ID does not exist. * `FAILED_PRECONDITION` if the requested user's
     * account is disabled, for the following request errors: *
     * CourseMemberLimitReached * CourseNotModifiable * CourseTeacherLimitReached *
     * UserGroupsMembershipLimitReached * `ALREADY_EXISTS` if the user is already a
     * teacher or student in the course. (teachers.create)
     *
     * @param string $courseId Identifier of the course. This identifier can be
     * either the Classroom-assigned identifier or an alias.
     * @param Google_Teacher $postBody
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_Teacher
     */
    public function create($courseId, Google_Service_Classroom_Teacher $postBody, $optParams = array())
    {
    }
    /**
     * Deletes a teacher of a course. This method returns the following error codes:
     * * `PERMISSION_DENIED` if the requesting user is not permitted to delete
     * teachers of this course or for access errors. * `NOT_FOUND` if no teacher of
     * this course has the requested ID or if the course does not exist. *
     * `FAILED_PRECONDITION` if the requested ID belongs to the primary teacher of
     * this course. (teachers.delete)
     *
     * @param string $courseId Identifier of the course. This identifier can be
     * either the Classroom-assigned identifier or an alias.
     * @param string $userId Identifier of the teacher to delete. The identifier can
     * be one of the following: * the numeric identifier for the user * the email
     * address of the user * the string literal `"me"`, indicating the requesting
     * user
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_Empty
     */
    public function delete($courseId, $userId, $optParams = array())
    {
    }
    /**
     * Returns a teacher of a course. This method returns the following error codes:
     * * `PERMISSION_DENIED` if the requesting user is not permitted to view
     * teachers of this course or for access errors. * `NOT_FOUND` if no teacher of
     * this course has the requested ID or if the course does not exist.
     * (teachers.get)
     *
     * @param string $courseId Identifier of the course. This identifier can be
     * either the Classroom-assigned identifier or an alias.
     * @param string $userId Identifier of the teacher to return. The identifier can
     * be one of the following: * the numeric identifier for the user * the email
     * address of the user * the string literal `"me"`, indicating the requesting
     * user
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_Teacher
     */
    public function get($courseId, $userId, $optParams = array())
    {
    }
    /**
     * Returns a list of teachers of this course that the requester is permitted to
     * view. This method returns the following error codes: * `NOT_FOUND` if the
     * course does not exist. * `PERMISSION_DENIED` for access errors.
     * (teachers.listCoursesTeachers)
     *
     * @param string $courseId Identifier of the course. This identifier can be
     * either the Classroom-assigned identifier or an alias.
     * @param array $optParams Optional parameters.
     *
     * @opt_param string pageToken nextPageToken value returned from a previous list
     * call, indicating that the subsequent page of results should be returned. The
     * list request must be otherwise identical to the one that resulted in this
     * token.
     * @opt_param int pageSize Maximum number of items to return. Zero means no
     * maximum. The server may return fewer than the specified number of results.
     * @return Google_Service_Classroom_ListTeachersResponse
     */
    public function listCoursesTeachers($courseId, $optParams = array())
    {
    }
}
/**
 * The "invitations" collection of methods.
 * Typical usage is:
 *  <code>
 *   $classroomService = new Google_Service_Classroom(...);
 *   $invitations = $classroomService->invitations;
 *  </code>
 */
#[AllowDynamicProperties]
class Google_Service_Classroom_Invitations_Resource extends Google_Service_Resource
{
    /**
     * Accepts an invitation, removing it and adding the invited user to the
     * teachers or students (as appropriate) of the specified course. Only the
     * invited user may accept an invitation. This method returns the following
     * error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to
     * accept the requested invitation or for access errors. * `FAILED_PRECONDITION`
     * for the following request errors: * CourseMemberLimitReached *
     * CourseNotModifiable * CourseTeacherLimitReached *
     * UserGroupsMembershipLimitReached * `NOT_FOUND` if no invitation exists with
     * the requested ID. (invitations.accept)
     *
     * @param string $id Identifier of the invitation to accept.
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_Empty
     */
    public function accept($id, $optParams = array())
    {
    }
    /**
     * Creates an invitation. Only one invitation for a user and course may exist at
     * a time. Delete and re-create an invitation to make changes. This method
     * returns the following error codes: * `PERMISSION_DENIED` if the requesting
     * user is not permitted to create invitations for this course or for access
     * errors. * `NOT_FOUND` if the course or the user does not exist. *
     * `FAILED_PRECONDITION` if the requested user's account is disabled or if the
     * user already has this role or a role with greater permissions. *
     * `ALREADY_EXISTS` if an invitation for the specified user and course already
     * exists. (invitations.create)
     *
     * @param Google_Invitation $postBody
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_Invitation
     */
    public function create(Google_Service_Classroom_Invitation $postBody, $optParams = array())
    {
    }
    /**
     * Deletes an invitation. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not permitted to delete the
     * requested invitation or for access errors. * `NOT_FOUND` if no invitation
     * exists with the requested ID. (invitations.delete)
     *
     * @param string $id Identifier of the invitation to delete.
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_Empty
     */
    public function delete($id, $optParams = array())
    {
    }
    /**
     * Returns an invitation. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not permitted to view the
     * requested invitation or for access errors. * `NOT_FOUND` if no invitation
     * exists with the requested ID. (invitations.get)
     *
     * @param string $id Identifier of the invitation to return.
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_Invitation
     */
    public function get($id, $optParams = array())
    {
    }
    /**
     * Returns a list of invitations that the requesting user is permitted to view,
     * restricted to those that match the list request. *Note:* At least one of
     * `user_id` or `course_id` must be supplied. Both fields can be supplied. This
     * method returns the following error codes: * `PERMISSION_DENIED` for access
     * errors. (invitations.listInvitations)
     *
     * @param array $optParams Optional parameters.
     *
     * @opt_param string courseId Restricts returned invitations to those for a
     * course with the specified identifier.
     * @opt_param string pageToken nextPageToken value returned from a previous list
     * call, indicating that the subsequent page of results should be returned. The
     * list request must be otherwise identical to the one that resulted in this
     * token.
     * @opt_param string userId Restricts returned invitations to those for a
     * specific user. The identifier can be one of the following: * the numeric
     * identifier for the user * the email address of the user * the string literal
     * `"me"`, indicating the requesting user
     * @opt_param int pageSize Maximum number of items to return. Zero means no
     * maximum. The server may return fewer than the specified number of results.
     * @return Google_Service_Classroom_ListInvitationsResponse
     */
    public function listInvitations($optParams = array())
    {
    }
}
/**
 * The "userProfiles" collection of methods.
 * Typical usage is:
 *  <code>
 *   $classroomService = new Google_Service_Classroom(...);
 *   $userProfiles = $classroomService->userProfiles;
 *  </code>
 */
#[AllowDynamicProperties]
class Google_Service_Classroom_UserProfiles_Resource extends Google_Service_Resource
{
    /**
     * Returns a user profile. This method returns the following error codes: *
     * `PERMISSION_DENIED` if the requesting user is not permitted to access this
     * user profile or if no profile exists with the requested ID or for access
     * errors. (userProfiles.get)
     *
     * @param string $userId Identifier of the profile to return. The identifier can
     * be one of the following: * the numeric identifier for the user * the email
     * address of the user * the string literal `"me"`, indicating the requesting
     * user
     * @param array $optParams Optional parameters.
     * @return Google_Service_Classroom_UserProfile
     */
    public function get($userId, $optParams = array())
    {
    }
}
#[AllowDynamicProperties]
class Google_Service_Classroom_Course extends Google_Model
{
    protected $internal_gapi_mappings = array();
    public $alternateLink;
    public $courseState;
    public $creationTime;
    public $description;
    public $descriptionHeading;
    public $enrollmentCode;
    public $id;
    public $name;
    public $ownerId;
    public $room;
    public $section;
    public $updateTime;
    public function setAlternateLink($alternateLink)
    {
    }
    public function getAlternateLink()
    {
    }
    public function setCourseState($courseState)
    {
    }
    public function getCourseState()
    {
    }
    public function setCreationTime($creationTime)
    {
    }
    public function getCreationTime()
    {
    }
    public function setDescription($description)
    {
    }
    public function getDescription()
    {
    }
    public function setDescriptionHeading($descriptionHeading)
    {
    }
    public function getDescriptionHeading()
    {
    }
    public function setEnrollmentCode($enrollmentCode)
    {
    }
    public function getEnrollmentCode()
    {
    }
    public function setId($id)
    {
    }
    public function getId()
    {
    }
    public function setName($name)
    {
    }
    public function getName()
    {
    }
    public function setOwnerId($ownerId)
    {
    }
    public function getOwnerId()
    {
    }
    public function setRoom($room)
    {
    }
    public function getRoom()
    {
    }
    public function setSection($section)
    {
    }
    public function getSection()
    {
    }
    public function setUpdateTime($updateTime)
    {
    }
    public function getUpdateTime()
    {
    }
}
#[AllowDynamicProperties]
class Google_Service_Classroom_CourseAlias extends Google_Model
{
    protected $internal_gapi_mappings = array();
    public $alias;
    public function setAlias($alias)
    {
    }
    public function getAlias()
    {
    }
}
#[AllowDynamicProperties]
class Google_Service_Classroom_Empty extends Google_Model
{
}
#[AllowDynamicProperties]
class Google_Service_Classroom_GlobalPermission extends Google_Model
{
    protected $internal_gapi_mappings = array();
    public $permission;
    public function setPermission($permission)
    {
    }
    public function getPermission()
    {
    }
}
#[AllowDynamicProperties]
class Google_Service_Classroom_Invitation extends Google_Model
{
    protected $internal_gapi_mappings = array();
    public $courseId;
    public $id;
    public $role;
    public $userId;
    public function setCourseId($courseId)
    {
    }
    public function getCourseId()
    {
    }
    public function setId($id)
    {
    }
    public function getId()
    {
    }
    public function setRole($role)
    {
    }
    public function getRole()
    {
    }
    public function setUserId($userId)
    {
    }
    public function getUserId()
    {
    }
}
#[AllowDynamicProperties]
class Google_Service_Classroom_ListCourseAliasesResponse extends Google_Collection
{
    protected $collection_key = 'aliases';
    protected $internal_gapi_mappings = array();
    protected $aliasesType = 'Google_Service_Classroom_CourseAlias';
    protected $aliasesDataType = 'array';
    public $nextPageToken;
    public function setAliases($aliases)
    {
    }
    public function getAliases()
    {
    }
    public function setNextPageToken($nextPageToken)
    {
    }
    public function getNextPageToken()
    {
    }
}
#[AllowDynamicProperties]
class Google_Service_Classroom_ListCoursesResponse extends Google_Collection
{
    protected $collection_key = 'courses';
    protected $internal_gapi_mappings = array();
    protected $coursesType = 'Google_Service_Classroom_Course';
    protected $coursesDataType = 'array';
    public $nextPageToken;
    public function setCourses($courses)
    {
    }
    public function getCourses()
    {
    }
    public function setNextPageToken($nextPageToken)
    {
    }
    public function getNextPageToken()
    {
    }
}
#[AllowDynamicProperties]
class Google_Service_Classroom_ListInvitationsResponse extends Google_Collection
{
    protected $collection_key = 'invitations';
    protected $internal_gapi_mappings = array();
    protected $invitationsType = 'Google_Service_Classroom_Invitation';
    protected $invitationsDataType = 'array';
    public $nextPageToken;
    public function setInvitations($invitations)
    {
    }
    public function getInvitations()
    {
    }
    public function setNextPageToken($nextPageToken)
    {
    }
    public function getNextPageToken()
    {
    }
}
#[AllowDynamicProperties]
class Google_Service_Classroom_ListStudentsResponse extends Google_Collection
{
    protected $collection_key = 'students';
    protected $internal_gapi_mappings = array();
    public $nextPageToken;
    protected $studentsType = 'Google_Service_Classroom_Student';
    protected $studentsDataType = 'array';
    public function setNextPageToken($nextPageToken)
    {
    }
    public function getNextPageToken()
    {
    }
    public function setStudents($students)
    {
    }
    public function getStudents()
    {
    }
}
#[AllowDynamicProperties]
class Google_Service_Classroom_ListTeachersResponse extends Google_Collection
{
    protected $collection_key = 'teachers';
    protected $internal_gapi_mappings = array();
    public $nextPageToken;
    protected $teachersType = 'Google_Service_Classroom_Teacher';
    protected $teachersDataType = 'array';
    public function setNextPageToken($nextPageToken)
    {
    }
    public function getNextPageToken()
    {
    }
    public function setTeachers($teachers)
    {
    }
    public function getTeachers()
    {
    }
}
#[AllowDynamicProperties]
class Google_Service_Classroom_Name extends Google_Model
{
    protected $internal_gapi_mappings = array();
    public $familyName;
    public $fullName;
    public $givenName;
    public function setFamilyName($familyName)
    {
    }
    public function getFamilyName()
    {
    }
    public function setFullName($fullName)
    {
    }
    public function getFullName()
    {
    }
    public function setGivenName($givenName)
    {
    }
    public function getGivenName()
    {
    }
}
#[AllowDynamicProperties]
class Google_Service_Classroom_Student extends Google_Model
{
    protected $internal_gapi_mappings = array();
    public $courseId;
    protected $profileType = 'Google_Service_Classroom_UserProfile';
    protected $profileDataType = '';
    public $userId;
    public function setCourseId($courseId)
    {
    }
    public function getCourseId()
    {
    }
    public function setProfile(Google_Service_Classroom_UserProfile $profile)
    {
    }
    public function getProfile()
    {
    }
    public function setUserId($userId)
    {
    }
    public function getUserId()
    {
    }
}
#[AllowDynamicProperties]
class Google_Service_Classroom_Teacher extends Google_Model
{
    protected $internal_gapi_mappings = array();
    public $courseId;
    protected $profileType = 'Google_Service_Classroom_UserProfile';
    protected $profileDataType = '';
    public $userId;
    public function setCourseId($courseId)
    {
    }
    public function getCourseId()
    {
    }
    public function setProfile(Google_Service_Classroom_UserProfile $profile)
    {
    }
    public function getProfile()
    {
    }
    public function setUserId($userId)
    {
    }
    public function getUserId()
    {
    }
}
#[AllowDynamicProperties]
class Google_Service_Classroom_UserProfile extends Google_Collection
{
    protected $collection_key = 'permissions';
    protected $internal_gapi_mappings = array();
    public $emailAddress;
    public $id;
    protected $nameType = 'Google_Service_Classroom_Name';
    protected $nameDataType = '';
    protected $permissionsType = 'Google_Service_Classroom_GlobalPermission';
    protected $permissionsDataType = 'array';
    public $photoUrl;
    public function setEmailAddress($emailAddress)
    {
    }
    public function getEmailAddress()
    {
    }
    public function setId($id)
    {
    }
    public function getId()
    {
    }
    public function setName(Google_Service_Classroom_Name $name)
    {
    }
    public function getName()
    {
    }
    public function setPermissions($permissions)
    {
    }
    public function getPermissions()
    {
    }
    public function setPhotoUrl($photoUrl)
    {
    }
    public function getPhotoUrl()
    {
    }
}