<?php

/**
 * Auto-generated stub file for Moodle's public/lib/google2-service/src/CloudNumberRegistry/AggregatedData.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
/*
 * Copyright 2014 Google Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
namespace Google\Service\CloudNumberRegistry {
    class AggregatedData extends \Google\Model
    {
        /**
         * Output only. Number of CustomRanges in the RegistryBook.
         *
         * @var int
         */
        public $customRangesCount;
        /**
         * Output only. Number of custom Realms in the RegistryBook.
         *
         * @var int
         */
        public $customRealmsCount;
        /**
         * Output only. Number of DiscoveredRanges in the RegistryBook.
         *
         * @var int
         */
        public $discoveredRangesCount;
        /**
         * Output only. Number of discovered Realms in the RegistryBook.
         *
         * @var int
         */
        public $discoveredRealmsCount;
        /**
         * Output only. Number of scopes unique to the RegistryBook.
         *
         * @var int
         */
        public $uniqueScopesCount;
        /**
         * Output only. Number of CustomRanges in the RegistryBook.
         *
         * @param int $customRangesCount
         */
        public function setCustomRangesCount($customRangesCount)
        {
        }
        /**
         * @return int
         */
        public function getCustomRangesCount()
        {
        }
        /**
         * Output only. Number of custom Realms in the RegistryBook.
         *
         * @param int $customRealmsCount
         */
        public function setCustomRealmsCount($customRealmsCount)
        {
        }
        /**
         * @return int
         */
        public function getCustomRealmsCount()
        {
        }
        /**
         * Output only. Number of DiscoveredRanges in the RegistryBook.
         *
         * @param int $discoveredRangesCount
         */
        public function setDiscoveredRangesCount($discoveredRangesCount)
        {
        }
        /**
         * @return int
         */
        public function getDiscoveredRangesCount()
        {
        }
        /**
         * Output only. Number of discovered Realms in the RegistryBook.
         *
         * @param int $discoveredRealmsCount
         */
        public function setDiscoveredRealmsCount($discoveredRealmsCount)
        {
        }
        /**
         * @return int
         */
        public function getDiscoveredRealmsCount()
        {
        }
        /**
         * Output only. Number of scopes unique to the RegistryBook.
         *
         * @param int $uniqueScopesCount
         */
        public function setUniqueScopesCount($uniqueScopesCount)
        {
        }
        /**
         * @return int
         */
        public function getUniqueScopesCount()
        {
        }
    }
}
namespace {
    /**
     * Runtime class alias of \Google\Service\CloudNumberRegistry\AggregatedData registered by the original source,
     * re-emitted as a declaration so static analysers can resolve the name.
     */
    class Google_Service_CloudNumberRegistry_AggregatedData extends \Google\Service\CloudNumberRegistry\AggregatedData
    {
    }
}