<?php

/**
 * Auto-generated stub file for Moodle's public/lib/aws-sdk/src/Exception/UnresolvedSignatureException.php
 *
 * @generated by bimoo — https://github.com/michaelmeneses/bimoo
 * @link https://github.com/michaelmeneses/moodle-stubs
 */
namespace Aws\Exception;

class UnresolvedSignatureException extends \RuntimeException implements MonitoringEventsInterface
{
    use HasMonitoringEventsTrait;
}